import { Body,Controller,Get,HttpCode,Inject,Param,Patch,Post,Query } from "@nestjs/common";
import { Throttle } from "@nestjs/throttler";
import { Public,RequireAnyPermission,RequireIdentityKinds } from "../authentication/authentication.decorators.js";
import { IdentityContextAccessor } from "../security/identity-context.js";
import { TenantContextAccessor } from "../tenancy/tenant-context.js";
import { CreateCustomerQuoteDto,CreatePricingProfileDto,CreatePricingRuleDto,SelectCustomerOfferDto,UpsertParticipationDto } from "./customer-quote.dto.js";
import { CustomerQuoteService } from "./customer-quote.service.js";
@Controller("public/customer-quotes") export class PublicCustomerQuoteController{constructor(@Inject(CustomerQuoteService) private readonly service:CustomerQuoteService){} @Public() @Throttle({default:{limit:8,ttl:60000}}) @HttpCode(201) @Post() create(@Body()body:CreateCustomerQuoteDto){return this.service.create(body);} @Public() @Throttle({default:{limit:20,ttl:60000}}) @Get(":reference") result(@Param("reference")reference:string,@Query("token")token:string){return this.service.publicResult(reference,token??"");} @Public() @Throttle({default:{limit:8,ttl:60000}}) @Post(":reference/select") select(@Param("reference")reference:string,@Body()body:SelectCustomerOfferDto){return this.service.select(reference,body.accessToken,body.publicOfferId);}}
@RequireIdentityKinds("company_user") @RequireAnyPermission("customer_quote_pricing.manage","users_roles.manage") @Controller("customer-quote-marketplace") export class CompanyCustomerQuoteController{constructor(@Inject(CustomerQuoteService) private readonly service:CustomerQuoteService,@Inject(TenantContextAccessor) private readonly tenants:TenantContextAccessor,@Inject(IdentityContextAccessor) private readonly identity:IdentityContextAccessor){}private company(){return this.tenants.current().companyId;} @Get("configuration") configuration(){return this.service.companyOverview(this.company());} @Patch("participation") participation(@Body()body:UpsertParticipationDto){return this.service.setParticipation(this.company(),this.identity.current().identityId,body);} @Post("profiles") profile(@Body()body:CreatePricingProfileDto){return this.service.createProfile(this.company(),this.identity.current().identityId,body);} @Post("profiles/:id/rules") rule(@Param("id")id:string,@Body()body:CreatePricingRuleDto){return this.service.createRule(this.company(),id,body);} @Patch("profiles/:id/activate") activate(@Param("id")id:string){return this.service.activateProfile(this.company(),id);} @Get("opportunities") opportunities(){return this.service.companyOpportunities(this.company());}}
