import type { AccountingOperationalArea } from "./accounting-ownership.matrix.js";

export type AccountingMappingField =
  | "creditAccountId"
  | "debitAccountId"
  | "expenseAccountId"
  | "feeAccountId"
  | "payableAccountId"
  | "vatAccountId";

export interface AccountingMandatoryMappingDefinition {
  readonly key: string;
  readonly label: string;
  readonly area: AccountingOperationalArea | "core";
  readonly requirement: "mandatory" | "conditional";
  readonly accountType: "asset" | "liability" | "equity" | "revenue" | "expense";
  readonly accountClasses: readonly string[];
  readonly field: AccountingMappingField;
  readonly controlType?: string;
  readonly synonyms: readonly string[];
  readonly readinessImpact: "manual_accounting" | "automatic_posting";
}

const definition = (
  value: AccountingMandatoryMappingDefinition,
): AccountingMandatoryMappingDefinition => value;

export const accountingMandatoryMappings = [
  definition({
    key: "order_cod_receivable",
    label: "Order COD Receivable",
    area: "orders",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["accounts_receivable"],
    field: "debitAccountId",
    controlType: "accounts_receivable",
    synonyms: ["accounts receivable", "trade receivable", "ذمم مدينة", "المدينون"],
    readinessImpact: "manual_accounting",
  }),
  definition({
    key: "delivery_revenue",
    label: "Delivery Revenue",
    area: "orders",
    requirement: "mandatory",
    accountType: "revenue",
    accountClasses: ["delivery_revenue"],
    field: "creditAccountId",
    synonyms: ["delivery revenue", "delivery income", "إيراد التوصيل"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "service_fee_revenue",
    label: "Service Fee Revenue",
    area: "orders",
    requirement: "mandatory",
    accountType: "revenue",
    accountClasses: ["service_fee_revenue"],
    field: "creditAccountId",
    synonyms: ["service fee revenue", "service income", "إيراد رسوم الخدمة"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "additional_fee_revenue",
    label: "Additional Fee Revenue",
    area: "orders",
    requirement: "conditional",
    accountType: "revenue",
    accountClasses: ["additional_fee_revenue", "other_operating_revenue"],
    field: "creditAccountId",
    synonyms: ["additional fee revenue", "other revenue", "إيرادات إضافية"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "output_vat",
    label: "Output VAT",
    area: "orders",
    requirement: "conditional",
    accountType: "liability",
    accountClasses: ["vat_payable"],
    field: "vatAccountId",
    synonyms: ["output vat", "vat payable", "ضريبة مخرجات", "ضريبة مستحقة"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "trader_payable",
    label: "Trader Payable",
    area: "trader_settlements",
    requirement: "mandatory",
    accountType: "liability",
    accountClasses: ["trader_payable"],
    field: "payableAccountId",
    controlType: "trader_payable",
    synonyms: ["trader payable", "merchant payable", "ذمم التجار"],
    readinessImpact: "manual_accounting",
  }),
  definition({
    key: "trader_settlement_cash",
    label: "Trader Settlement Cash",
    area: "trader_settlements",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "creditAccountId",
    synonyms: ["main cash", "cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "trader_settlement_bank",
    label: "Trader Settlement Bank",
    area: "trader_settlements",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["bank"],
    field: "creditAccountId",
    synonyms: ["main bank", "bank", "current account", "بنك", "حساب جاري"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "driver_collection_cash",
    label: "Driver Collection Cash",
    area: "driver_collections",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "debitAccountId",
    synonyms: ["main cash", "cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "driver_collection_fee_offset",
    label: "Driver Collection Fee Offset",
    area: "driver_collections",
    requirement: "mandatory",
    accountType: "liability",
    accountClasses: ["driver_payable"],
    field: "payableAccountId",
    controlType: "driver_payable",
    synonyms: ["driver payable", "مستحقات السائقين"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "driver_expense",
    label: "Driver Expense",
    area: "driver_expenses",
    requirement: "mandatory",
    accountType: "expense",
    accountClasses: ["driver_expense"],
    field: "expenseAccountId",
    synonyms: ["driver expense", "مصروف السائق"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "employee_payroll_expense",
    label: "Salary Expense",
    area: "employee_payroll",
    requirement: "mandatory",
    accountType: "expense",
    accountClasses: ["payroll_expense"],
    field: "expenseAccountId",
    synonyms: ["salary expense", "payroll expense", "مصروف الرواتب"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "employee_payroll_payable",
    label: "Payroll Payable",
    area: "employee_payroll",
    requirement: "mandatory",
    accountType: "liability",
    accountClasses: ["payroll_payable"],
    field: "payableAccountId",
    controlType: "payroll_payable",
    synonyms: ["payroll payable", "salary payable", "رواتب مستحقة"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "employee_payroll_cash_payment",
    label: "Payroll Cash",
    area: "employee_payroll",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "creditAccountId",
    synonyms: ["main cash", "cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "employee_interim_payroll_clearing",
    label: "Employee Interim Payroll Clearing",
    area: "employee_payroll",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["prepaid_expense"],
    field: "debitAccountId",
    controlType: "employee_interim_payroll_clearing",
    synonyms: ["employee interim payroll clearing", "interim payroll clearing"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "employee_advances",
    label: "Employee Advances",
    area: "employee_payroll",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["prepaid_expense"],
    field: "debitAccountId",
    controlType: "employee_advances",
    synonyms: ["employee advances", "salary advances"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "outsourced_driver_fee_expense",
    label: "Outsourced Driver Expense",
    area: "outsourced_driver_fees",
    requirement: "mandatory",
    accountType: "expense",
    accountClasses: ["outsourced_driver_fee_expense", "driver_expense"],
    field: "expenseAccountId",
    synonyms: ["outsourced driver expense", "driver fee expense", "مصروف السائق الخارجي"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "outsourced_driver_payable",
    label: "Outsourced Driver Payable",
    area: "outsourced_driver_fees",
    requirement: "mandatory",
    accountType: "liability",
    accountClasses: ["driver_payable"],
    field: "payableAccountId",
    controlType: "driver_payable",
    synonyms: ["driver payable", "مستحقات السائقين"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "outsourced_driver_cash_payment",
    label: "Outsourced Driver Cash",
    area: "outsourced_driver_fees",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "creditAccountId",
    synonyms: ["main cash", "cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "general_expense",
    label: "General Expense",
    area: "general_expenses",
    requirement: "mandatory",
    accountType: "expense",
    accountClasses: ["general_expense", "administrative_expense"],
    field: "expenseAccountId",
    synonyms: ["general expense", "administrative expense", "مصروفات عامة", "مصروفات إدارية"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "input_vat",
    label: "Input VAT",
    area: "general_expenses",
    requirement: "conditional",
    accountType: "asset",
    accountClasses: ["accounts_receivable", "other_receivable", "prepaid_expense", "other_asset"],
    field: "vatAccountId",
    synonyms: ["input vat", "vat receivable", "ضريبة مدخلات"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "general_expense_payable",
    label: "General Expense Payable",
    area: "general_expenses",
    requirement: "mandatory",
    accountType: "liability",
    accountClasses: ["accounts_payable"],
    field: "payableAccountId",
    controlType: "accounts_payable",
    synonyms: ["accounts payable", "expense payable", "ذمم دائنة"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "general_expense_cash_payment",
    label: "Expense Cash Payment",
    area: "general_expenses",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "creditAccountId",
    synonyms: ["main cash", "cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "general_expense_bank_payment",
    label: "Expense Bank Payment",
    area: "general_expenses",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["bank"],
    field: "creditAccountId",
    synonyms: ["main bank", "bank", "current account", "بنك", "حساب جاري"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_transfer",
    label: "Cash Transfer",
    area: "cash_bank_management",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["cash"],
    field: "debitAccountId",
    synonyms: ["cash", "الصندوق", "نقد"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "bank_transfer",
    label: "Bank Transfer",
    area: "cash_bank_management",
    requirement: "mandatory",
    accountType: "asset",
    accountClasses: ["bank"],
    field: "debitAccountId",
    synonyms: ["bank", "current account", "بنك", "حساب جاري"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "bank_charge",
    label: "Bank Charges",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "expense",
    accountClasses: ["bank_charge"],
    field: "expenseAccountId",
    synonyms: ["bank charges", "bank fees", "رسوم بنكية"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_deposit_owner_contribution",
    label: "Owner Equity",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "equity",
    accountClasses: ["owner_equity", "share_capital"],
    field: "creditAccountId",
    synonyms: ["owner equity", "capital", "رأس المال", "حقوق الملكية"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_deposit_refund",
    label: "Cash or Bank Refund Deposit",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "expense",
    accountClasses: ["general_expense", "administrative_expense", "other_expense"],
    field: "creditAccountId",
    synonyms: ["expense refund", "refund received", "استرداد مصروف"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_deposit_loan",
    label: "Loan Deposit",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "liability",
    accountClasses: ["other_liability"],
    field: "creditAccountId",
    synonyms: ["loan payable", "loan received", "قرض مستحق"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_withdrawal_owner",
    label: "Owner Withdrawal",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "equity",
    accountClasses: ["owner_equity", "other_equity"],
    field: "debitAccountId",
    synonyms: ["owner drawings", "owner withdrawal", "مسحوبات المالك"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_withdrawal_refund",
    label: "Customer Refund",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "liability",
    accountClasses: ["other_liability", "accounts_payable"],
    field: "debitAccountId",
    synonyms: ["customer refund", "refund payable", "رد مبلغ للعميل"],
    readinessImpact: "automatic_posting",
  }),
  definition({
    key: "cash_bank_withdrawal_loan_repayment",
    label: "Loan Repayment",
    area: "cash_bank_management",
    requirement: "conditional",
    accountType: "liability",
    accountClasses: ["other_liability"],
    field: "debitAccountId",
    synonyms: ["loan payable", "loan repayment", "سداد قرض"],
    readinessImpact: "automatic_posting",
  }),
] as const;

export const accountingSetupMappingsByArea = {
  orders: [
    "order_cod_receivable",
    "delivery_revenue",
    "service_fee_revenue",
    "additional_fee_revenue",
    "trader_payable",
    "output_vat",
  ],
  trader_receivables: [
    "order_cod_receivable",
    "additional_fee_revenue",
    "trader_settlement_cash",
    "trader_settlement_bank",
  ],
  trader_settlements: ["trader_payable", "trader_settlement_cash", "trader_settlement_bank"],
  driver_collections: [
    "order_cod_receivable",
    "driver_collection_cash",
    "trader_settlement_bank",
    "driver_expense",
    "driver_collection_fee_offset",
  ],
  driver_expenses: ["driver_expense"],
  employee_payroll: [
    "employee_payroll_expense",
    "employee_payroll_payable",
    "employee_payroll_cash_payment",
    "employee_interim_payroll_clearing",
    "employee_advances",
  ],
  outsourced_driver_fees: [
    "outsourced_driver_fee_expense",
    "outsourced_driver_payable",
    "outsourced_driver_cash_payment",
  ],
  general_expenses: [
    "general_expense",
    "input_vat",
    "general_expense_payable",
    "general_expense_cash_payment",
    "general_expense_bank_payment",
  ],
  cash_bank_management: [
    "bank_charge",
    "cash_bank_deposit_owner_contribution",
    "cash_bank_deposit_refund",
    "cash_bank_deposit_loan",
    "cash_bank_withdrawal_owner",
    "cash_bank_withdrawal_refund",
    "cash_bank_withdrawal_loan_repayment",
  ],
} as const satisfies Readonly<Record<AccountingOperationalArea, readonly string[]>>;
