import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { useTranslation } from "react-i18next";
import type { ApiClient } from "../../api/api-client.js";
import { ApiError } from "../../api/api-client.js";
import type { Emirate, OperationsDriver, OperationsTrader } from "../../api/contracts.js";
import { normalizeLocale } from "../../localization/locale.js";

const statuses = ["new", "in_branch", "assigned_to_driver", "out_for_delivery", "hold", "delivered", "returned_to_branch", "returned_to_trader", "cancelled", "closed", "collect_order"] as const;
type Row = { orderNumber:string; referenceNumber?:string | null; orderDate:string; deliveryDate:string | null; traderName:string; customer:string; customerMobile:string; emirates:string; area:string; cod:string; fee:string; traderAmount:string; paidToTrader:string; collectedFromTrader:string; balance:string; status:string };
/** Totals cover every order matching the filters (all pages), from the server. */
/** Trader Amount and Balance arrive without sign; each total is the plain sum of what is shown. */
type Totals = { cod: string; fee: string; traderAmount: string; paidToTrader: string; collectedFromTrader: string; balance: string };
const balanceTypes = ["due_to_trader", "due_from_trader", "settled"] as const;
const settlementStatuses = ["unsettled", "money_sent_to_trader", "money_received_by_trader", "not_eligible"] as const;
/** Reference Numbers typed as a list: commas (English or Arabic), semicolons or new lines. */
export function parseReferenceNumbers(value: string): string[] { return [...new Set(value.split(/[,،;\n\r]+/u).map((item) => item.trim()).filter((item) => item.length > 0))]; }
type Page = { items: Row[]; page: number; pageSize: number; totalCount: number; totals?: Totals };

export function OrdersReport({ api }: { api: ApiClient }) {
  const { t, i18n } = useTranslation();
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [trader, setTrader] = useState("");
  const [selected, setSelected] = useState<string[]>([]); const [referenceDraft, setReferenceDraft] = useState(""); const [references, setReferences] = useState<string[]>([]); const [page, setPage] = useState(1); const [data, setData] = useState<Page>();
  const [deliveryFrom, setDeliveryFrom] = useState(""); const [deliveryTo, setDeliveryTo] = useState(""); const [emirateId, setEmirateId] = useState(""); const [areaDraft, setAreaDraft] = useState(""); const [area, setArea] = useState(""); const [driverId, setDriverId] = useState(""); const [customerDraft, setCustomerDraft] = useState(""); const [customer, setCustomer] = useState(""); const [balanceType, setBalanceType] = useState(""); const [settlementStatus, setSettlementStatus] = useState("");
  const [emirates, setEmirates] = useState<readonly Emirate[]>([]); const [drivers, setDrivers] = useState<readonly OperationsDriver[]>([]);
  const [traders, setTraders] = useState<readonly OperationsTrader[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [exporting, setExporting] = useState(false); const [exportError, setExportError] = useState<string | null>(null);
  const query = useMemo(() => { const p = new URLSearchParams(); if (from) p.set("dateFrom", from); if (to) p.set("dateTo", to); if (trader) p.set("traderId", trader); if (selected.length) p.set("statuses", selected.join(",")); if (references.length) p.set("references", references.join(",")); const extra: Record<string, string> = { deliveryFrom, deliveryTo, emirateId, area, driverId, customer, balanceType, settlementStatus }; for (const [key, value] of Object.entries(extra)) if (value) p.set(key, value); p.set("page", String(page)); p.set("pageSize", "25"); return p.toString(); }, [from,to,trader,selected,references,deliveryFrom,deliveryTo,emirateId,area,driverId,customer,balanceType,settlementStatus,page]);
  useEffect(() => { void api.get<readonly OperationsTrader[]>("operations/traders").then(setTraders).catch(() => setError(true)); }, [api]);
  // Optional lookups: if the user cannot read them, that filter simply stays hidden.
  useEffect(() => { void api.get<readonly Emirate[]>("configuration/emirates").then((list) => setEmirates(Array.isArray(list) ? list : [])).catch(() => setEmirates([])); }, [api]);
  useEffect(() => { void api.get<readonly OperationsDriver[]>("operations/drivers?includeInactive=true").then((list) => setDrivers(Array.isArray(list) ? list : [])).catch(() => setDrivers([])); }, [api]);
  useEffect(() => { setLoading(true); setError(false); void api.get<Page>(`operations/reports/orders?${query}`).then(setData).catch(() => setError(true)).finally(() => setLoading(false)); }, [api, query]);
  const exportFile = async (format: "xlsx" | "pdf") => { if (exporting) return; setExporting(true); setExportError(null); try { const p = new URLSearchParams(query); p.delete("page"); p.delete("pageSize"); if (format === "pdf") p.set("language", normalizeLocale(i18n.resolvedLanguage)); const blob = await api.getBinary(`operations/reports/orders.${format}?${p}`); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href=url; a.download=`orders-report.${format}`; a.click(); URL.revokeObjectURL(url); } catch (error) { const detail = error instanceof ApiError && error.correlationId ? ` (${error.correlationId})` : ""; setExportError(`${error instanceof Error ? error.message : t("reports.orders.exportFailed")}${detail}`); } finally { setExporting(false); } };
  // Applied on Enter or when leaving the field, not on every keystroke.
  const applyReferences = () => { const next = parseReferenceNumbers(referenceDraft); if (next.join(",") !== references.join(",")) { setReferences(next); setPage(1); } };
  const applyText = (draft: string, current: string, set: (value: string) => void) => { const next = draft.trim(); if (next !== current) { set(next); setPage(1); } };
  const textFilter = (key: "area" | "customer", draft: string, setDraft: (value: string) => void, current: string, set: (value: string) => void) => <label>{t(`reports.orders.filters.${key}`)}<input type="text" data-testid={`orders-report-${key}`} placeholder={t(`reports.orders.filters.${key}Placeholder`)} value={draft} onChange={(e) => setDraft(e.target.value)} onBlur={() => applyText(draft, current, set)} onKeyDown={(e) => { if (e.key === "Enter") applyText(draft, current, set); }} /></label>;
  const resetPage = <T,>(set: (value: T) => void) => (value: T) => { set(value); setPage(1); };
  const arabicNames = normalizeLocale(i18n.resolvedLanguage) === "ar";
  const toggle = (status: string) => setSelected((current) => current.includes(status) ? current.filter((v) => v !== status) : [...current, status]);
  const pages = Math.max(1, Math.ceil((data?.totalCount ?? 0) / 25));
  // One Trader selected: show its name once above the table (in red) and drop
  // the repeated Trader Name column.
  const selectedTraderName = trader === "" ? undefined : traders.find((item) => item.id === trader)?.name;
  const singleTrader = selectedTraderName !== undefined;
  const columns = ["serial", "referenceNumber", "orderDate", "deliveryDate", ...(singleTrader ? [] : ["traderName"]), "customer", "customerMobile", "emirates", "area", "cod", "fee", "traderAmount", "paidToTrader", "collectedFromTrader", "balance", "status"] as const;
  const columnStyle: Record<string, CSSProperties> = { serial: { whiteSpace: "nowrap", width: "3rem" }, referenceNumber: { whiteSpace: "nowrap" }, orderDate: { whiteSpace: "nowrap" }, deliveryDate: { whiteSpace: "nowrap" }, customerMobile: { whiteSpace: "nowrap" }, emirates: { minWidth: "8rem" }, area: { minWidth: "11rem" }, collectedFromTrader: { width: "6.5rem" } };
  const labelColumns = columns.indexOf("cod");
  return <section className="reports-panel" aria-label={t("reports.orders.title")}>
    <div className="report-actions"><div><h2>{t("reports.orders.title")}</h2><p>{t("reports.orders.subtitle")}</p></div><div className="report-export-actions"><button className="button button-primary" disabled={exporting} onClick={() => void exportFile("xlsx")} type="button">{t("reports.orders.export")}</button><button className="button" disabled={exporting} onClick={() => void exportFile("pdf")} type="button">{t("reports.orders.exportPdf")}</button></div></div>
    {exportError ? <div className="alert alert-error" role="alert">{exportError}</div> : null}
    <div className="orders-report-filters"><label>{t("reports.orders.from")}<input type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(1); }} /></label><label>{t("reports.orders.to")}<input type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(1); }} /></label><label>{t("reports.orders.trader")}<select value={trader} onChange={(e) => { setTrader(e.target.value); setPage(1); }}><option value="">{t("reports.orders.allTraders")}</option>{traders.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t("reports.orders.references")}<input type="text" data-testid="orders-report-references" placeholder={t("reports.orders.referencesPlaceholder")} value={referenceDraft} onChange={(e) => setReferenceDraft(e.target.value)} onBlur={applyReferences} onKeyDown={(e) => { if (e.key === "Enter") applyReferences(); }} /></label></div>
    <div className="orders-report-filters" data-testid="orders-report-more-filters"><label>{t("reports.orders.filters.deliveryFrom")}<input type="date" value={deliveryFrom} onChange={(e) => resetPage(setDeliveryFrom)(e.target.value)} /></label><label>{t("reports.orders.filters.deliveryTo")}<input type="date" value={deliveryTo} onChange={(e) => resetPage(setDeliveryTo)(e.target.value)} /></label>{emirates.length > 0 ? <label>{t("reports.orders.filters.emirate")}<select data-testid="orders-report-emirate" value={emirateId} onChange={(e) => resetPage(setEmirateId)(e.target.value)}><option value="">{t("reports.orders.filters.allEmirates")}</option>{emirates.map((item) => <option key={item.id} value={item.id}>{arabicNames ? item.nameAr || item.nameEn : item.nameEn}</option>)}</select></label> : null}{textFilter("area", areaDraft, setAreaDraft, area, setArea)}{drivers.length > 0 ? <label>{t("reports.orders.filters.driver")}<select data-testid="orders-report-driver" value={driverId} onChange={(e) => resetPage(setDriverId)(e.target.value)}><option value="">{t("reports.orders.filters.allDrivers")}</option>{drivers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}{textFilter("customer", customerDraft, setCustomerDraft, customer, setCustomer)}<label>{t("reports.orders.filters.balanceType")}<select data-testid="orders-report-balance-type" value={balanceType} onChange={(e) => resetPage(setBalanceType)(e.target.value)}><option value="">{t("reports.orders.filters.any")}</option>{balanceTypes.map((value) => <option key={value} value={value}>{t(`reports.orders.filters.balanceTypes.${value}`)}</option>)}</select></label><label>{t("reports.orders.filters.settlementStatus")}<select data-testid="orders-report-settlement" value={settlementStatus} onChange={(e) => resetPage(setSettlementStatus)(e.target.value)}><option value="">{t("reports.orders.filters.any")}</option>{settlementStatuses.map((value) => <option key={value} value={value}>{t(`reports.orders.filters.settlementStatuses.${value}`)}</option>)}</select></label></div>
    <fieldset className="orders-report-statuses"><legend>{t("reports.orders.status")}</legend><label><input type="checkbox" checked={selected.length === statuses.length} onChange={() => setSelected(selected.length === statuses.length ? [] : [...statuses])} />{t("reports.orders.allStatuses")}</label>{statuses.map((status) => <label key={status}><input type="checkbox" checked={selected.includes(status)} onChange={() => toggle(status)} />{t(`statuses.${status}`)}</label>)}</fieldset>
    {error ? <div className="alert alert-error" role="alert">{t("common.loadFailed")}</div> : null}{loading ? <div className="loading-row">{t("common.loading")}</div> : null}
    {!loading && !error && (data?.items.length ?? 0) === 0 ? <div className="empty-state">{t("reports.orders.empty")}</div> : null}
    {(data?.items.length ?? 0) > 0 ? <><p>{t("reports.orders.total", { count: data?.totalCount ?? 0 })}</p>{data?.totals ? <div className="orders-report-totals" data-testid="orders-report-totals" style={{ display: "flex", flexWrap: "wrap", gap: "1.5rem", margin: "0.25rem 0 0.75rem" }}><span>{t("reports.orders.totalCod")}: <strong>{data.totals.cod}</strong></span><span>{t("reports.orders.totalFee")}: <strong>{data.totals.fee}</strong></span><span>{t("reports.orders.totalTraderAmount")}: <strong>{data.totals.traderAmount}</strong></span><span>{t("reports.orders.totalPaidToTrader")}: <strong>{data.totals.paidToTrader}</strong></span><span>{t("reports.orders.totalCollectedFromTrader")}: <strong>{data.totals.collectedFromTrader}</strong></span><span>{t("reports.orders.totalBalance")}: <strong>{data.totals.balance}</strong></span></div> : null}<div className="table-scroll">{singleTrader ? <p className="orders-report-trader" data-testid="orders-report-trader" style={{ color: "#c62828", fontSize: "1.15rem", fontWeight: 700, margin: "0.25rem 0" }}>{t("reports.orders.trader")}: {selectedTraderName}</p> : null}<table><thead><tr>{columns.map((key) => <th key={key} style={columnStyle[key]}>{t(`reports.orders.columns.${key}`)}</th>)}</tr></thead><tbody>{data?.items.map((row, index) => <tr key={row.orderNumber}><td style={columnStyle.serial}>{(page - 1) * 25 + index + 1}</td><td style={columnStyle.referenceNumber}>{row.referenceNumber ?? ""}</td><td style={columnStyle.orderDate}>{row.orderDate}</td><td style={columnStyle.deliveryDate}>{row.deliveryDate ?? ""}</td>{singleTrader ? null : <td>{row.traderName}</td>}<td>{row.customer}</td><td style={columnStyle.customerMobile}>{row.customerMobile}</td><td style={columnStyle.emirates}>{row.emirates}</td><td style={columnStyle.area}>{row.area}</td><td>{row.cod}</td><td>{row.fee}</td><td>{row.traderAmount}</td><td>{row.paidToTrader}</td><td>{row.collectedFromTrader}</td><td>{row.balance}</td><td>{t(`statuses.${row.status}`)}</td></tr>)}</tbody>{data?.totals ? <tfoot><tr><th colSpan={labelColumns} scope="row">{t("reports.orders.totalsRow")}</th><th>{data.totals.cod}</th><th>{data.totals.fee}</th><th>{data.totals.traderAmount}</th><th>{data.totals.paidToTrader}</th><th>{data.totals.collectedFromTrader}</th><th>{data.totals.balance}</th><th /></tr></tfoot> : null}</table></div><div className="pagination"><button disabled={page<=1} onClick={() => setPage(page-1)} type="button">{t("common.previous")}</button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={() => setPage(page+1)} type="button">{t("common.next")}</button></div></> : null}
  </section>;
}
