import { validate } from "class-validator";
import { plainToInstance } from "class-transformer";
import { PUBLIC_ROUTE, REQUIRED_IDENTITY_KINDS, REQUIRED_PERMISSIONS } from "../authentication/authentication.decorators.js";
import { CreateDemoRequestDto } from "./demo-request.dto.js";
import { normalizeMobile } from "./demo-request.service.js";
import { PublicDemoRequestController } from "./public-demo-request.controller.js";
import { PlatformDemoRequestController } from "../platform/platform-demo-request.controller.js";

const valid={companyName:"Atlas Delivery",contactPerson:"Amina Noor",mobileNumber:"0501234567",email:"amina@example.ae",country:"United Arab Emirates",emirate:"dubai",preferredContactMethod:"phone",featuresOfInterest:["order_management"],consent:true,landingPage:"/request-demo"};
describe("demo request public contract",()=>{it("accepts a valid qualification request",async()=>expect(await validate(plainToInstance(CreateDemoRequestDto,valid))).toHaveLength(0));it("accepts a non-UAE prospect without emirate or selected features",async()=>expect(await validate(plainToInstance(CreateDemoRequestDto,{...valid,mobileNumber:"+966 50 123 4567",country:"Saudi Arabia",emirate:undefined,featuresOfInterest:undefined}))).toHaveLength(0));it("rejects invalid email and oversized text",async()=>{const errors=await validate(plainToInstance(CreateDemoRequestDto,{...valid,email:"invalid",companyName:"x".repeat(201)}));expect(errors.map(error=>error.property)).toEqual(expect.arrayContaining(["email","companyName"]));});it("forbids injected workflow fields through the global whitelist contract",()=>{expect(Object.prototype.hasOwnProperty.call(new CreateDemoRequestDto(),"status")).toBe(false);});it("normalizes supported UAE mobile formats",()=>{expect(normalizeMobile("050 123 4567")).toBe("+971501234567");expect(normalizeMobile("+971 50 123 4567")).toBe("+971501234567");});it("accepts international mobile numbers",()=>expect(normalizeMobile("+966 50 123 4567")).toBe("+966501234567"));it("rejects invalid mobile numbers",()=>expect(()=>normalizeMobile("12345")).toThrow());});
describe("demo request route authorization",()=>{it("makes only submission public",()=>{expect(Reflect.getMetadata(PUBLIC_ROUTE,PublicDemoRequestController.prototype.create)).toBe(true);expect(Reflect.getMetadata(PUBLIC_ROUTE,PlatformDemoRequestController.prototype.list)).not.toBe(true);});it("requires Platform identity and lead permissions for management",()=>{const handler=PlatformDemoRequestController.prototype.status;expect(Reflect.getMetadata(REQUIRED_IDENTITY_KINDS,handler)).toContain("platform_administrator");expect(Reflect.getMetadata(REQUIRED_PERMISSIONS,handler)).toEqual(expect.arrayContaining(["platform.access","platform.leads.manage"]));});});
