import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { vi } from "vitest";

import type { ApiClient } from "../../api/api-client.js";
import { i18nInstance } from "../../localization/i18n.js";
import { AccountingResourcePage } from "./AccountingResourcePage.js";

/**
 * The General Expense create form.
 *
 * Two things are pinned here, through the real `AccountingResourcePage` (not
 * just the dialog and `RecordForm` in isolation, covered separately):
 *
 * 1. Inline "+ Add Category" sits beside the TOP `categoryId` field only.
 * 2. The form is operator-facing, not a raw accounting-line builder: Category
 *    + Description + Amount is everything required. The single accounting
 *    line the backend needs (`GeneralExpenseLineDto`) is generated by
 *    `submitCreate`, not typed by hand -- quantity, unit amount, VAT
 *    treatment/rate, recoverable %, and the expense-account mapping key are
 *    never shown on this form. VAT treatment/rate come from the selected
 *    Category's own `defaultVatTreatment` (required on every Category) and,
 *    for a `standard_rated` Category, the Company's configured VAT rate.
 */

const officeCategory = {
  code: "EXP-OFFICE",
  defaultExpenseMappingKey: "general_expense",
  defaultVatTreatment: "out_of_scope",
  id: "cat-office",
  nameEn: "Office Supplies",
};
const petrolCategory = {
  code: "EXP-PETROL-FUEL",
  defaultExpenseMappingKey: "general_expense",
  defaultVatTreatment: "out_of_scope",
  id: "cat-petrol",
  nameEn: "Petrol / Fuel",
};
// Present specifically to prove a `standard_rated` Category pulls its rate
// from the Company's own VAT settings rather than asking the operator.
const importDutyCategory = {
  code: "EXP-IMPORT",
  defaultExpenseMappingKey: "general_expense",
  defaultVatTreatment: "standard_rated",
  id: "cat-import",
  nameEn: "Import Duty",
};
const generalExpenseMapping = {
  expenseAccountCode: "5030",
  expenseAccountId: "acc-5030",
  isActive: true,
  mappingKey: "general_expense",
};
const glAccounts = [
  {
    accountType: "expense",
    id: "acc-5030",
    isActive: true,
    isPostingAccount: true,
    nameEn: "General Expense",
  },
];

function buildApi(
  options: {
    readonly categories?: readonly unknown[];
    readonly categoriesAfterCreate?: readonly unknown[];
    readonly companySettings?: unknown;
  } = {},
) {
  let categories: readonly unknown[] = options.categories ?? [officeCategory];
  const post = vi.fn((path: string) => {
    if (path === "operations/accounting/general-expenses/categories") {
      categories = options.categoriesAfterCreate ?? [officeCategory, petrolCategory];
      return Promise.resolve({ id: "cat-petrol" });
    }
    if (path === "operations/accounting/general-expenses") {
      return Promise.resolve({ id: "exp-1" });
    }
    return Promise.resolve({});
  });
  const get = vi.fn((path: string) => {
    if (path.startsWith("operations/accounting/general-expenses/categories"))
      return Promise.resolve(categories);
    if (path === "operations/accounting/mappings") return Promise.resolve([generalExpenseMapping]);
    if (path === "operations/accounting/accounts") return Promise.resolve(glAccounts);
    if (path.startsWith("operations/accounting/general-expenses"))
      return Promise.resolve({ items: [], total: 0 });
    // Fetched directly through the raw `ApiClient`, NOT through `AccountingApi`
    // (no `operations/accounting` prefix) -- the same endpoint the Accounting
    // Configuration screen itself reads Company VAT settings from.
    if (path === "configuration/settings") {
      return Promise.resolve(
        options.companySettings ?? { vatEnabled: false, vatPriceMode: null, vatRate: null },
      );
    }
    return Promise.resolve({});
  });
  return { api: { get, post } as unknown as ApiClient, post };
}

const renderPage = (permissions: readonly string[], api: ApiClient) =>
  render(
    <MemoryRouter>
      <AccountingResourcePage
        api={api}
        companyId="company-1"
        onNavigate={vi.fn()}
        permissions={permissions}
        section="expenses"
      />
    </MemoryRouter>,
  );

const openCreateForm = async () => {
  fireEvent.click(await screen.findByRole("button", { name: "Create" }));
  await screen.findByLabelText(/Amount/, {}, { timeout: 3000 });
};

// Two "Create" buttons coexist once the form is open: the page header's
// trigger and the form's own submit. The one that actually submits is the
// only `type="submit"`.
const submitCreateButton = () =>
  screen
    .getAllByRole("button", { name: "Create" })
    .find((button) => button.getAttribute("type") === "submit")!;

describe("General Expense create form — inline Add Category", () => {
  beforeEach(async () => i18nInstance.changeLanguage("en"));

  it("shows + Add Category for a user who can manage Categories", async () => {
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();
    expect(await screen.findByRole("button", { name: "+ Add Category" })).toBeInTheDocument();
  });

  /* There is no permission split for this feature to hide behind: creating a
     General Expense and managing Categories both require the SAME permission,
     `accounting.manage` (`definition.permission` for the "expenses" section).
     A `accounting.view`-only user cannot reach the create form at all, so
     "+ Add Category" is provably absent for them the same way everything
     else that needs `manage` is -- proven here by there being nothing to
     click into in the first place, never a leaked control elsewhere. */
  it("never renders + Add Category for a user without accounting.manage", async () => {
    const { api } = buildApi();
    renderPage(["accounting.view"], api);
    await screen.findByText("General Expenses");
    expect(screen.queryByRole("button", { name: "Create" })).toBeNull();
    expect(screen.queryByRole("button", { name: "+ Add Category" })).toBeNull();
  });

  it("opens the modal without leaving the General Expense screen", async () => {
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();
    fireEvent.click(await screen.findByRole("button", { name: "+ Add Category" }));
    expect(await screen.findByText("Create Expense Category")).toBeInTheDocument();
    // The General Expense form is still mounted underneath -- this is a
    // modal, not a navigation.
    expect(screen.getByLabelText(/Amount/)).toBeInTheDocument();
  });

  it("places + Add Category beside the TOP categoryId field", async () => {
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    expect(screen.getAllByRole("button", { name: "+ Add Category" })).toHaveLength(1);
    const categoryField = screen.getByLabelText(/categoryId/);
    expect(
      within(categoryField.parentElement!).getByRole("button", { name: "+ Add Category" }),
    ).toBeInTheDocument();
  });

  it("creates a Category, auto-selects it, and preserves the rest of the form", async () => {
    const { api, post } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    // Fields entered BEFORE adding the Category.
    fireEvent.change(screen.getByLabelText(/^Payee/), { target: { value: "ADNOC Station" } });
    fireEvent.change(screen.getByLabelText(/^Description/), {
      target: { value: "Fuel for Van 3" },
    });

    fireEvent.click(await screen.findByRole("button", { name: "+ Add Category" }));
    const dialog = within(await screen.findByRole("dialog"));
    fireEvent.change(dialog.getByLabelText(/Category Name/), {
      target: { value: "Petrol / Fuel" },
    });
    await dialog.findByText("General Expense (5030)");
    fireEvent.click(dialog.getByRole("button", { name: "Save" }));

    await waitFor(() =>
      expect(post).toHaveBeenCalledWith(
        "operations/accounting/general-expenses/categories",
        expect.objectContaining({ nameEn: "Petrol / Fuel" }),
        expect.anything(),
      ),
    );
    // Modal closed, and the newly created Category is selected on the one
    // Category field the form has.
    await waitFor(() => expect(screen.queryByText("Create Expense Category")).toBeNull());
    await waitFor(() => expect(screen.getByLabelText(/categoryId/)).toHaveValue("cat-petrol"));

    // Untouched fields, exactly as entered before the modal opened.
    expect(screen.getByLabelText(/^Payee/)).toHaveValue("ADNOC Station");
    expect(screen.getByLabelText(/^Description/)).toHaveValue("Fuel for Van 3");
  });

  it("Cancel closes the dialog and leaves the Category list unchanged", async () => {
    const { api, post } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();
    fireEvent.click(await screen.findByRole("button", { name: "+ Add Category" }));
    const dialog = within(await screen.findByRole("dialog"));
    fireEvent.change(dialog.getByLabelText(/Category Name/), { target: { value: "Petrol" } });

    fireEvent.click(dialog.getByRole("button", { name: "Cancel" }));

    expect(screen.queryByText("Create Expense Category")).toBeNull();
    expect(post).not.toHaveBeenCalled();
    const options = within(screen.getByLabelText(/categoryId/)).getAllByRole("option");
    expect(options.map((option) => option.textContent)).toEqual([
      "Select",
      "EXP-OFFICE — Office Supplies",
    ]);
  });
});

/**
 * The simplified, operator-facing General Expense create form.
 *
 * Proves (per the correction spec): the technical accounting-line block is
 * gone; Category and Amount remain the only things an operator provides
 * beyond the header fields; a standard Expense can be created without ever
 * touching a line/mapping/VAT-technical field; and the generated API payload
 * is the same shape the backend has always required.
 */
describe("General Expense create form — simplified, no technical line fields", () => {
  beforeEach(async () => i18nInstance.changeLanguage("en"));

  it("does not render the technical accounting-line block", async () => {
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    for (const label of [
      /Line category ID/,
      /Line description/,
      /Quantity/,
      /Unit amount/,
      /VAT treatment/,
      /VAT rate/,
      /Recoverable percentage/,
      /Expense Account mapping key/,
    ]) {
      expect(screen.queryByLabelText(label)).toBeNull();
    }
  });

  it("keeps the top Category field, with + Add Category beside it, and an Amount field", async () => {
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    expect(screen.getByLabelText(/categoryId/)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "+ Add Category" })).toBeInTheDocument();
    expect(screen.getByLabelText(/Amount/)).toBeInTheDocument();
  });

  it("creates a standard Expense from Category + Description + Amount alone", async () => {
    const { api, post } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    fireEvent.change(screen.getByLabelText(/categoryId/), { target: { value: "cat-office" } });
    fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Petrol" } });
    fireEvent.change(screen.getByLabelText(/Amount/), { target: { value: "100" } });

    fireEvent.click(submitCreateButton());

    await waitFor(() =>
      expect(post).toHaveBeenCalledWith(
        "operations/accounting/general-expenses",
        expect.anything(),
        expect.anything(),
      ),
    );
  });

  it("generates the underlying API payload correctly: one line, backend line-shape unchanged", async () => {
    const { api, post } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    fireEvent.change(screen.getByLabelText(/categoryId/), { target: { value: "cat-office" } });
    fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Petrol" } });
    fireEvent.change(screen.getByLabelText(/Amount/), { target: { value: "100" } });

    fireEvent.click(submitCreateButton());

    await waitFor(() =>
      expect(post).toHaveBeenCalledWith(
        "operations/accounting/general-expenses",
        expect.objectContaining({
          categoryId: "cat-office",
          description: "Petrol",
          lines: [
            expect.objectContaining({
              categoryId: "cat-office",
              description: "Petrol",
              quantity: "1",
              unitAmount: "100",
              vatRate: "0",
              vatTreatment: "out_of_scope",
            }),
          ],
        }),
        expect.anything(),
      ),
    );
    // No mapping key sent -- the backend falls back to the Category's own
    // `defaultExpenseMappingKey` when a line omits it.
    const call = post.mock.calls.find(
      (args) => args[0] === "operations/accounting/general-expenses",
    ) as unknown as [string, { lines: readonly { expenseAccountMappingKey?: unknown }[] }];
    expect(call[1].lines[0]).not.toHaveProperty("expenseAccountMappingKey");
  });

  it("uses the Company's configured VAT rate for a standard_rated Category, and 0% for everything else", async () => {
    const { api, post } = buildApi({
      categories: [officeCategory, importDutyCategory],
      companySettings: { vatEnabled: true, vatPriceMode: "exclusive", vatRate: "5" },
    });
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    fireEvent.change(screen.getByLabelText(/categoryId/), { target: { value: "cat-import" } });
    fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Customs duty" } });
    fireEvent.change(screen.getByLabelText(/Amount/), { target: { value: "200" } });
    fireEvent.click(submitCreateButton());

    await waitFor(() =>
      expect(post).toHaveBeenCalledWith(
        "operations/accounting/general-expenses",
        expect.objectContaining({
          lines: [expect.objectContaining({ vatRate: "5", vatTreatment: "standard_rated" })],
        }),
        expect.anything(),
      ),
    );
  });

  it("renders in Arabic with the Category field, its Add-Category button and Amount all usable", async () => {
    await i18nInstance.changeLanguage("ar");
    const { api } = buildApi();
    renderPage(["accounting.manage"], api);
    fireEvent.click(await screen.findByRole("button", { name: "إنشاء" }));
    await screen.findByLabelText(/Amount|المبلغ/, {}, { timeout: 3000 });

    expect(screen.getByRole("button", { name: "+ إضافة فئة" })).toBeInTheDocument();
    expect(screen.getByLabelText(/Amount|المبلغ/)).toBeInTheDocument();
    await i18nInstance.changeLanguage("en");
  });

  it("leaves the existing accounting result unaffected: header fields still post as before", async () => {
    const { api, post } = buildApi();
    renderPage(["accounting.manage"], api);
    await openCreateForm();

    fireEvent.change(screen.getByLabelText(/categoryId/), { target: { value: "cat-office" } });
    fireEvent.change(screen.getByLabelText(/^Payee/), { target: { value: "Landlord" } });
    fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Rent" } });
    fireEvent.change(screen.getByLabelText(/Amount/), { target: { value: "500" } });

    fireEvent.click(submitCreateButton());

    await waitFor(() =>
      expect(post).toHaveBeenCalledWith(
        "operations/accounting/general-expenses",
        expect.objectContaining({ payeeName: "Landlord" }),
        expect.anything(),
      ),
    );
  });
});
