import { Transform } from "class-transformer";
import { IsEmail, IsIn, IsString, Length, Matches } from "class-validator";

import { NormalizeUaeMobile } from "../shared/uae-mobile.js";

/**
 * Company user request contracts for the Platform API.
 *
 * The global pipe runs `whitelist` + `forbidNonWhitelisted`, so anything not
 * declared here is REJECTED rather than stripped. That is what keeps the
 * following out of the request surface entirely — there is simply no field:
 *
 *   companyId · accountId · roleIds · permissions · passwordHash ·
 *   password · tokenHash · createdBy · lockedUntil · failedLoginAttempts
 *
 * The Company comes from the route and is re-resolved server-side; the role is
 * chosen by the server; the credential is established by the user through a
 * one-time link, never supplied by an administrator.
 */
const trim = ({ value }: { value: unknown }): unknown =>
  typeof value === "string" ? value.trim() : value;

export class CreateCompanyAdministratorDto {
  /**
   * One Name field, which may hold Arabic or English. The product's established
   * rule; no separate Arabic/English pair is introduced here.
   */
  @Transform(trim)
  @IsString()
  @Length(2, 200)
  public displayName!: string;

  /**
   * Login identifier. Unique PER COMPANY, not globally
   * (`accounts_company_normalized_username_unique`), so two Companies may each
   * have an `admin`.
   */
  @Transform(({ value }: { value: unknown }) => (typeof value === "string" ? value.trim() : value))
  @IsString()
  @Length(3, 128)
  @Matches(/^[A-Za-z0-9][A-Za-z0-9._-]{2,127}$/, {
    message: "username must be 3-128 characters using letters, digits and . _ -",
  })
  public username!: string;

  @Transform(({ value }: { value: unknown }) =>
    typeof value === "string" ? value.trim().toLowerCase() : value,
  )
  @IsEmail()
  @Length(3, 320)
  public email!: string;

  /**
   * Normalised to the canonical `9715XXXXXXXX` form by the SAME decorator the
   * Company portal's own user screens use. `accounts_mobile_format` accepts
   * nothing else, and a Platform-created account must satisfy exactly the rules
   * a Company-created one does.
   */
  @NormalizeUaeMobile()
  @Matches(/^9715[0-9]{8}$/, {
    message: "Enter a UAE mobile number, for example 0506468442 or 9715XXXXXXXX.",
  })
  public mobileNumber!: string;

  @IsIn(["en", "ar"])
  public preferredLanguage!: "en" | "ar";
}

/** A reason is required for actions someone will later be asked to explain. */
export class AccountReasonDto {
  @Transform(trim)
  @IsString()
  @Length(3, 500)
  public reason!: string;
}

/**
 * The typed confirmation for permanent user deletion.
 *
 * The expected phrase is generated by the SERVER from the account's username
 * (`DELETE <username>`) and compared server-side. A challenge the client
 * composed would confirm nothing -- the browser would simply be agreeing with
 * itself about which account it had asked to delete.
 *
 * There is deliberately no `force`, `skipChecks` or `reason`-as-override field:
 * eligibility is not something the caller can assert.
 */
export class DeleteCompanyUserDto {
  @IsString()
  @Length(1, 200)
  public confirmation!: string;
}
