import { Type } from "class-transformer";
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEmail,
  IsIn,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from "class-validator";

import { NormalizeUaeMobile } from "../shared/uae-mobile.js";

const mobilePattern = /^9715[0-9]{8}$/;

export class CreateAllowanceTypeDto {
  @Matches(/^[A-Za-z0-9_-]{2,32}$/)
  public readonly code!: string;

  @IsString()
  @MaxLength(160)
  public readonly name!: string;
}

export class EmployeeAllowanceDto {
  @IsUUID()
  public readonly allowanceTypeId!: string;

  @IsNumber()
  @Min(0)
  public readonly amount!: number;

  @IsDateString()
  public readonly effectiveFrom!: string;

  @IsOptional()
  @IsDateString()
  public readonly effectiveTo?: string;
}

const mobileMessage = {
  message: "Enter a UAE mobile number, for example 0506468442 or 9715XXXXXXXX.",
};

/**
 * Employee is the master workforce entity. Its role (Customer Service, Driver,
 * ...) is chosen from the configurable list. When the role is a driver role the
 * engagement decides compensation: "employee" is salaried with allowances,
 * "outsourced" has no salary and a fixed fee per delivered order. The Employee
 * number is backend-generated and never submitted.
 */
export class SaveEmployeeDto {
  @IsUUID()
  public readonly employeeRoleId!: string;

  @IsOptional()
  @IsIn(["employee", "outsourced"])
  public readonly engagement?: "employee" | "outsourced";

  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly outsourcedFeePerDeliveredOrder?: number;

  @IsString()
  @MaxLength(160)
  public readonly name!: string;

  @NormalizeUaeMobile()
  @Matches(mobilePattern, mobileMessage)
  public readonly mobileNumber!: string;

  @IsOptional()
  @NormalizeUaeMobile()
  @Matches(mobilePattern, mobileMessage)
  public readonly secondMobileNumber?: string;

  @IsOptional()
  @IsEmail()
  @MaxLength(160)
  public readonly email?: string;

  @IsOptional()
  @IsString()
  @MaxLength(300)
  public readonly address?: string;

  @IsOptional()
  @IsUUID()
  public readonly areaId?: string;

  @IsOptional()
  @IsDateString()
  public readonly dateOfBirth?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  public readonly nationality?: string;

  @IsOptional()
  @IsDateString()
  public readonly joiningDate?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  public readonly jobTitle?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  public readonly department?: string;

  @IsOptional()
  @IsString()
  @MaxLength(80)
  public readonly employeeType?: string;

  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly basicSalary?: number;

  @IsOptional()
  @IsBoolean()
  public readonly payrollEligible?: boolean;

  @IsOptional()
  @IsBoolean()
  public readonly salaryHold?: boolean;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  public readonly salaryHoldReason?: string;

  @IsOptional()
  @IsDateString()
  public readonly salaryHoldFrom?: string;

  @IsOptional()
  @IsDateString()
  public readonly salaryHoldTo?: string;

  @IsOptional()
  @IsDateString()
  public readonly salaryEffectiveFrom?: string;

  @IsOptional()
  @IsUUID()
  public readonly userId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  public readonly notes?: string;

  @IsOptional()
  @IsArray()
  @ArrayMaxSize(4)
  @ValidateNested({ each: true })
  @Type(() => EmployeeAllowanceDto)
  public readonly allowances?: EmployeeAllowanceDto[];
}

/** Create a configurable Employee role (e.g. Customer Service, Driver). */
export class CreateEmployeeRoleDto {
  @IsString()
  @MaxLength(80)
  public readonly name!: string;

  @IsOptional()
  @IsBoolean()
  public readonly isDriverRole?: boolean;
}

/**
 * The unified Driver form. There is no separate Employee entity in the UI:
 *   driverType "employee"   -> salaried, with optional allowances (a backing
 *                              Employee record is created behind the scenes so
 *                              payroll keeps working)
 *   driverType "outsourced" -> no salary, only a fixed fee per delivered order
 *
 * The Driver code and the backing Employee number are generated by the backend;
 * neither is entered here.
 */
export class SaveDriverDto {
  @IsString()
  @MaxLength(160)
  public readonly name!: string;

  @IsIn(["employee", "outsourced"])
  public readonly driverType!: "employee" | "outsourced";

  @NormalizeUaeMobile()
  @Matches(mobilePattern, {
    message: "Enter a UAE mobile number, for example 0506468442 or 9715XXXXXXXX.",
  })
  public readonly mobileNumber!: string;

  @IsOptional()
  @NormalizeUaeMobile()
  @Matches(mobilePattern, {
    message: "Enter a UAE mobile number, for example 0506468442 or 9715XXXXXXXX.",
  })
  public readonly secondMobileNumber?: string;

  @IsOptional()
  @IsEmail()
  @MaxLength(160)
  public readonly email?: string;

  @IsOptional()
  @IsString()
  @MaxLength(300)
  public readonly address?: string;

  @IsOptional()
  @IsUUID()
  public readonly areaId?: string;

  @IsOptional()
  @IsUUID()
  public readonly vehicleId?: string;

  @IsOptional()
  @IsUUID()
  public readonly thirdPartyCompanyId?: string;

  @IsOptional()
  @IsUUID()
  public readonly userId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  public readonly notes?: string;

  // --- Employee-type compensation (salary + allowances) --------------------
  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly basicSalary?: number;

  @IsOptional()
  @IsDateString()
  public readonly salaryEffectiveFrom?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  public readonly jobTitle?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  public readonly department?: string;

  @IsOptional()
  @IsArray()
  @ArrayMaxSize(4)
  @ValidateNested({ each: true })
  @Type(() => EmployeeAllowanceDto)
  public readonly allowances?: EmployeeAllowanceDto[];

  // --- Outsourced-type compensation (fixed fee per delivered order) ---------
  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly outsourcedFeePerDeliveredOrder?: number;
}

export class ChangeWorkforceStatusDto {
  @IsBoolean()
  public readonly isActive!: boolean;

  @IsString()
  @MaxLength(500)
  public readonly reason!: string;
}

export class CreateHrDocumentDto {
  @IsIn(["passport", "emirates_id", "driving_licence", "visa_residency", "other"])
  public readonly documentType!: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  public readonly documentNumber?: string;

  @IsOptional()
  @IsDateString()
  public readonly issueDate?: string;

  @IsOptional()
  @IsDateString()
  public readonly expiryDate?: string;

  @IsOptional()
  @IsString()
  @MaxLength(160)
  public readonly issuingAuthority?: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  public readonly description?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  public readonly licenceCategory?: string;

  @IsOptional()
  @IsString()
  @MaxLength(300)
  public readonly restrictions?: string;
}

export class CreateCommissionRuleDto {
  @IsString()
  @MaxLength(160)
  public readonly name!: string;

  @IsIn(["fixed", "percentage"])
  public readonly method!: "fixed" | "percentage";

  @IsNumber()
  @Min(0)
  @Max(1000000)
  public readonly rate!: number;

  @IsIn(["daily", "monthly"])
  public readonly frequency!: "daily" | "monthly";

  @IsDateString()
  public readonly effectiveFrom!: string;

  @IsOptional()
  @IsDateString()
  public readonly effectiveTo?: string;
}

export class RunCommissionCalculationDto {
  @IsIn(["daily", "monthly"])
  public readonly frequency!: "daily" | "monthly";

  @IsDateString()
  public readonly periodStart!: string;

  @IsDateString()
  public readonly periodEnd!: string;

  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly additions?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  public readonly deductions?: number;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  public readonly adjustmentReason?: string;
}

export class ConfirmOutsourcedPaymentDto {
  @IsIn(["cash", "bank_transfer"])
  public readonly paymentMethod!: "cash" | "bank_transfer";

  @IsDateString()
  public readonly paymentDate!: string;

  @IsOptional()
  @IsUUID()
  public readonly bankAccountId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(160)
  public readonly reference?: string;

  @Matches(/^[A-Za-z0-9._:-]{16,128}$/)
  public readonly idempotencyKey!: string;
}

/*
 * Employee Driver variable earnings.
 *
 * Deliberately separate from `SaveEmployeeDto`: a rate is effective-dated
 * history, not a property of the Employee record. Folding it into the Employee
 * PATCH would mean every profile edit implicitly restated the rate, which is
 * exactly the overwrite the rule tables exist to prevent.
 */
const earningDatePattern = /^\d{4}-\d{2}-\d{2}$/;

export class SaveDeliveryEarningRuleDto {
  /** Flat amount per delivered Order. Zero is not a rate, it is a mistake. */
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0.01)
  public readonly amountPerOrder!: number;

  @Matches(earningDatePattern)
  public readonly effectiveFrom!: string;

  /** Omitted means "still in force". */
  @IsOptional()
  @Matches(earningDatePattern)
  public readonly effectiveTo?: string;
}

export class SaveCollectionEarningRuleDto {
  @IsIn(["none", "per_collected_order"])
  public readonly collectionPaymentType!: "none" | "per_collected_order";

  /** Must be 0 for `none`, and above 0 for either paid type. */
  @IsNumber({ allowInfinity: false, allowNaN: false, maxDecimalPlaces: 2 })
  @Min(0)
  public readonly amount!: number;

  @Matches(earningDatePattern)
  public readonly effectiveFrom!: string;

  @IsOptional()
  @Matches(earningDatePattern)
  public readonly effectiveTo?: string;
}
