import { type Kysely, sql } from "kysely";
type MigrationDatabase=Record<string,never>;
export async function up(database:Kysely<MigrationDatabase>):Promise<void>{await sql`
create table platform_blog_categories(id uuid primary key default gen_random_uuid(),name text not null,slug text not null,language text not null default 'en' check(language in('en','ar')),description text,seo_title text,meta_description text,active boolean not null default true,sort_order integer not null default 100,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(language,slug));
create table platform_blog_authors(id uuid primary key default gen_random_uuid(),display_name text not null,role_title text,short_bio text,profile_image_storage_key text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table platform_blog_tags(id uuid primary key default gen_random_uuid(),name text not null,slug text not null,language text not null default 'en' check(language in('en','ar')),created_at timestamptz not null default now(),unique(language,slug));
create table platform_blog_articles(
 id uuid primary key default gen_random_uuid(),slug text not null,language text not null default 'en' check(language in('en','ar')),translation_group_id uuid,
 title text not null,excerpt text not null,content jsonb not null default '[]' check(jsonb_typeof(content)='array'),featured_image_storage_key text,featured_image_public_url text,featured_image_alt text,featured_image_caption text,featured_image_width integer,featured_image_height integer,
 author_id uuid not null references platform_blog_authors(id) on delete restrict,category_id uuid not null references platform_blog_categories(id) on delete restrict,
 status text not null default 'draft' check(status in('draft','scheduled','published','unpublished','archived')),
 seo_title text,meta_description text,canonical_url text,robots_index boolean not null default true,robots_follow boolean not null default true,social_title text,social_description text,social_image_url text,
 published_at timestamptz,scheduled_at timestamptz,updated_content_at timestamptz,
 created_by_account_id uuid references accounts(id) on delete set null,updated_by_account_id uuid references accounts(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(language,slug),check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),check((status='scheduled' and scheduled_at is not null) or status<>'scheduled'),check((featured_image_public_url is null and featured_image_alt is null) or (featured_image_public_url is not null and featured_image_alt is not null))
);
create index platform_blog_articles_public_idx on platform_blog_articles(language,status,published_at desc,scheduled_at);
create table platform_blog_article_tags(article_id uuid not null references platform_blog_articles(id) on delete restrict,tag_id uuid not null references platform_blog_tags(id) on delete restrict,primary key(article_id,tag_id));
create table platform_public_redirects(id uuid primary key default gen_random_uuid(),from_path text not null unique,to_path text not null,status_code integer not null default 301 check(status_code in(301,308)),created_at timestamptz not null default now(),created_by_account_id uuid references accounts(id) on delete set null,check(from_path<>to_path));
create table platform_public_site_settings(id boolean primary key default true check(id),canonical_base_url text not null default 'https://tawseelhub.com',default_site_title text not null default 'Tawseelhub | Delivery Operating System',default_meta_description text not null default 'Connected delivery operations for modern UAE delivery companies.',default_social_image text,search_console_verification text,gtm_container_id text,ga4_measurement_id text,analytics_enabled boolean not null default false,clarity_project_id text,clarity_enabled boolean not null default false,tracking_environment text not null default 'production' check(tracking_environment in('development','staging','production')),updated_at timestamptz not null default now(),updated_by_account_id uuid references accounts(id) on delete set null,check(gtm_container_id is null or gtm_container_id ~ '^GTM-[A-Z0-9]{4,12}$'),check(ga4_measurement_id is null or ga4_measurement_id ~ '^G-[A-Z0-9]{6,14}$'),check(clarity_project_id is null or clarity_project_id ~ '^[a-z0-9]{6,20}$'));
insert into platform_public_site_settings(id)values(true);
create table platform_blog_publication_history(id uuid primary key default gen_random_uuid(),article_id uuid not null references platform_blog_articles(id) on delete restrict,event_type text not null,old_status text,new_status text,actor_account_id uuid references accounts(id) on delete set null,detail jsonb not null default '{}',created_at timestamptz not null default now());
create function reject_blog_history_mutation()returns trigger language plpgsql as $$begin raise exception 'Blog publication history is append-only' using errcode='55000';end;$$;
create trigger blog_history_append_only before update or delete on platform_blog_publication_history for each row execute function reject_blog_history_mutation();
insert into platform_blog_authors(display_name,role_title)values('Tawseelhub Team','Delivery Operations Editorial Team');
insert into platform_blog_categories(name,slug,description,sort_order)values
('Delivery Operations','delivery-operations','Practical guidance for running reliable delivery operations.',10),('COD & Finance','cod-finance','Controls and practices for cash-on-delivery operations.',20),('Business Growth','business-growth','Sustainable growth for delivery businesses.',30),('Last-Mile Delivery','last-mile-delivery','UAE last-mile delivery practices.',40),('UAE Delivery Guides','uae-delivery-guides','Guides for UAE delivery teams and senders.',50),('Salla','salla','Planned Salla delivery workflow guidance.',60),('Shopify','shopify','Planned Shopify delivery workflow guidance.',70),('WooCommerce','woocommerce','Planned WooCommerce delivery workflow guidance.',80);
insert into permissions(code,description)values
('platform.blog.read','View Website Content'),('platform.blog.create','Create Blog drafts'),('platform.blog.edit','Edit Blog content'),('platform.blog.publish','Publish and unpublish Blog content'),('platform.blog.categories.manage','Manage Blog categories and authors'),('platform.public_site_settings.manage','Manage public SEO and tracking settings') on conflict(code)do update set description=excluded.description;
insert into role_permissions(role_id,permission_code)select r.id,p.code from roles r cross join(values('platform.blog.read'),('platform.blog.create'),('platform.blog.edit'),('platform.blog.publish'),('platform.blog.categories.manage'),('platform.public_site_settings.manage'))p(code)where r.company_id is null and lower(r.code)='platform_super_admin' on conflict do nothing;
`.execute(database)}
export async function down(database:Kysely<MigrationDatabase>):Promise<void>{await sql`delete from role_permissions where permission_code like 'platform.blog.%' or permission_code='platform.public_site_settings.manage';delete from permissions where code like 'platform.blog.%' or code='platform.public_site_settings.manage';drop table platform_blog_publication_history;drop function reject_blog_history_mutation();drop table platform_public_site_settings;drop table platform_public_redirects;drop table platform_blog_article_tags;drop table platform_blog_articles;drop table platform_blog_tags;drop table platform_blog_authors;drop table platform_blog_categories;`.execute(database)}
