import { type Kysely, sql } from "kysely";

type MigrationDatabase = Record<string, never>;

/**
 * Cash/Bank Movements generated by Driver Collections and Trader Settlements
 * are operational evidence of money moving through a Company account. Their
 * parent Collection/Settlement Event already owns the GL Journal.
 *
 * A former implementation also enqueued a second Event using the Movement as
 * the source. Those Events can never be authoritative: their event type tells
 * the loader to read a Collection/Settlement, while their source id identifies
 * a Cash/Bank Movement. Preserve those rows for audit, classify them as ignored
 * duplicates, and link each Movement to its real parent Event.
 *
 * A movement-sourced Event can also exist WITHOUT a parent Event: the former
 * implementation wrote it unconditionally, while parent capture was gated
 * (no accounting_configurations row, or the pre-20260804110000 area gate).
 * Such an Event has no owner to link and was never loadable either, so it is
 * classified as an ignored duplicate with its own marker and the Movement's
 * accounting_event_id legitimately stays null - the same shape the corrected
 * runtime produces for a Company that records no Accounting facts.
 */
export async function up(database: Kysely<MigrationDatabase>): Promise<void> {
  await sql`
    with redundant as (
      select r.id as redundant_event_id,
             r.company_id,
             r.source_entity_id as movement_id,
             p.id as parent_event_id
        from accounting_events r
        join accounting_events p
          on p.company_id=r.company_id
         and p.event_type=r.event_type
         and (
           (r.event_type='driver_collection_confirmed'
             and r.supplementary_metadata->>'source'='driver_collection'
             and p.source_entity_type='driver_reconciliation'
             and p.source_reference=r.supplementary_metadata->>'reconciliationNumber')
           or
           (r.event_type='trader_settlement_confirmed'
             and r.supplementary_metadata->>'source'='trader_settlement'
             and p.source_entity_type='trader_settlement'
             and p.source_reference=r.supplementary_metadata->>'settlementNumber')
         )
       where r.source_entity_type='cash_bank_movement'
         and r.journal_id is null
    )
    update cash_bank_movements m
       set accounting_event_id=redundant.parent_event_id,
           updated_at=now()
      from redundant
     where m.id=redundant.movement_id
       and m.company_id=redundant.company_id
       and m.accounting_event_id is null;

    with redundant as (
      select r.id, p.id as parent_event_id
        from accounting_events r
        join accounting_events p
          on p.company_id=r.company_id
         and p.event_type=r.event_type
         and (
           (r.event_type='driver_collection_confirmed'
             and r.supplementary_metadata->>'source'='driver_collection'
             and p.source_entity_type='driver_reconciliation'
             and p.source_reference=r.supplementary_metadata->>'reconciliationNumber')
           or
           (r.event_type='trader_settlement_confirmed'
             and r.supplementary_metadata->>'source'='trader_settlement'
             and p.source_entity_type='trader_settlement'
             and p.source_reference=r.supplementary_metadata->>'settlementNumber')
         )
       where r.source_entity_type='cash_bank_movement'
         and r.journal_id is null
    )
    update accounting_events e
       set processing_status='ignored_duplicate',
           processed_at=coalesce(processed_at,now()),
           error_code=null,
           error_metadata=null,
           supplementary_metadata=e.supplementary_metadata || jsonb_build_object(
             'duplicateClassification','represented_by_parent_event',
             'representedByAccountingEventId',redundant.parent_event_id
           )
      from redundant
     where e.id=redundant.id
       and e.processing_status not in ('posted','reversed','ignored_duplicate');

    update accounting_events e
       set processing_status='ignored_duplicate',
           processed_at=coalesce(processed_at,now()),
           error_code=null,
           error_metadata=null,
           supplementary_metadata=e.supplementary_metadata || jsonb_build_object(
             'duplicateClassification','no_owner_event_captured'
           )
     where e.source_entity_type='cash_bank_movement'
       and e.event_type in ('driver_collection_confirmed','trader_settlement_confirmed')
       and e.supplementary_metadata->>'source' in ('driver_collection','trader_settlement')
       and e.journal_id is null
       and e.processing_status not in ('posted','reversed','ignored_duplicate');

    do $$
    begin
      if exists (
        select 1
          from accounting_events r
         where r.source_entity_type='cash_bank_movement'
           and r.event_type in ('driver_collection_confirmed','trader_settlement_confirmed')
           and r.supplementary_metadata->>'source' in ('driver_collection','trader_settlement')
           and r.journal_id is null
           and r.processing_status<>'ignored_duplicate'
      ) then
        raise exception using errcode='23514',
          message='generated_cash_movement_duplicate_event_unclassified';
      end if;
      if exists (
        select 1
          from accounting_events r
          join cash_bank_movements m
            on m.company_id=r.company_id and m.id=r.source_entity_id
         where r.source_entity_type='cash_bank_movement'
           and r.event_type in ('driver_collection_confirmed','trader_settlement_confirmed')
           and r.supplementary_metadata->>'duplicateClassification'='represented_by_parent_event'
           and m.accounting_event_id is null
      ) then
        raise exception using errcode='23514',
          message='generated_cash_movement_parent_event_not_linked';
      end if;
    end
    $$;
  `.execute(database);
}

export async function down(database: Kysely<MigrationDatabase>): Promise<void> {
  await sql`
    update cash_bank_movements m
       set accounting_event_id=null,
           updated_at=now()
      from accounting_events r
     where r.company_id=m.company_id
       and r.source_entity_id=m.id
       and r.source_entity_type='cash_bank_movement'
       and r.supplementary_metadata->>'duplicateClassification'='represented_by_parent_event'
       and m.accounting_event_id=(r.supplementary_metadata->>'representedByAccountingEventId')::uuid;

    update accounting_events
       set processing_status='received',
           processed_at=null,
           supplementary_metadata=supplementary_metadata
             - 'duplicateClassification'
             - 'representedByAccountingEventId'
     where source_entity_type='cash_bank_movement'
       and supplementary_metadata->>'duplicateClassification'
             in ('represented_by_parent_event','no_owner_event_captured')
       and processing_status='ignored_duplicate';
  `.execute(database);
}
