import { type Kysely, sql } from "kysely";

type MigrationDatabase = Record<string, never>;

/**
 * Preserve historical Accounting Events while giving two previously
 * ambiguous cases their authoritative terminal classification:
 *
 * 1. A delivered Order whose customer amount due and Trader payable are both
 *    zero has no financial components and must not manufacture a zero Journal.
 * 2. Cash/Bank Movements generated by a General Expense payment are evidence
 *    of the payment. The parent payment Event owns the Journal, so the former
 *    movement Event is a duplicate and the Movement links to the parent.
 */
export async function up(database: Kysely<MigrationDatabase>): Promise<void> {
  await sql`
    alter table accounting_events drop constraint accounting_events_status_check;
    alter table accounting_events add constraint accounting_events_status_check check (
      processing_status in (
        'received','processing','validated','posted','failed','retry_pending',
        'blocked_configuration','reversed','ignored_duplicate',
        'ignored_no_accounting_required'
      )
    );

    update accounting_events e
       set processing_status='ignored_no_accounting_required',
           processed_at=coalesce(e.processed_at,now()),
           error_code=null,
           error_metadata=null,
           failure_category=null,
           safe_error_summary=null,
           supplementary_metadata=e.supplementary_metadata || jsonb_build_object(
             'terminalClassification','no_accounting_required',
             'classificationReason','zero_customer_due_and_trader_payable'
           )
      from orders o
     where o.id=e.source_entity_id
       and o.company_id=e.company_id
       and e.source_entity_type='order'
       and e.event_type='order_delivered'
       and e.journal_id is null
       and e.processing_status in ('failed','blocked_configuration','retry_pending')
       and o.customer_amount_due=0
       and o.trader_net_payable=0;

    with owners as (
      select redundant.id as redundant_event_id,
             redundant.company_id,
             movement.id as movement_id,
             parent.id as parent_event_id
        from accounting_events redundant
        join cash_bank_movements movement
          on movement.id=redundant.source_entity_id
         and movement.company_id=redundant.company_id
        join accounting_events parent
          on parent.company_id=redundant.company_id
         and parent.event_type='general_expense_payment_completed'
         and parent.source_entity_type='general_expense_payment'
         and parent.source_reference=split_part(movement.idempotency_identity,':',2)
       where redundant.event_type in ('cash_withdrawal_confirmed','bank_withdrawal_confirmed')
         and redundant.source_entity_type='general_expense_payment'
         and redundant.journal_id is null
         and movement.idempotency_identity like 'general_expense_payment:%'
    )
    update cash_bank_movements movement
       set accounting_event_id=owners.parent_event_id,
           updated_at=now()
      from owners
     where movement.id=owners.movement_id
       and movement.company_id=owners.company_id
       and movement.accounting_event_id is null;

    with owners as (
      select redundant.id as redundant_event_id,
             parent.id as parent_event_id
        from accounting_events redundant
        join cash_bank_movements movement
          on movement.id=redundant.source_entity_id
         and movement.company_id=redundant.company_id
        join accounting_events parent
          on parent.company_id=redundant.company_id
         and parent.event_type='general_expense_payment_completed'
         and parent.source_entity_type='general_expense_payment'
         and parent.source_reference=split_part(movement.idempotency_identity,':',2)
       where redundant.event_type in ('cash_withdrawal_confirmed','bank_withdrawal_confirmed')
         and redundant.source_entity_type='general_expense_payment'
         and redundant.journal_id is null
         and movement.idempotency_identity like 'general_expense_payment:%'
    )
    update accounting_events e
       set processing_status='ignored_duplicate',
           processed_at=coalesce(e.processed_at,now()),
           error_code=null,
           error_metadata=null,
           failure_category=null,
           safe_error_summary=null,
           supplementary_metadata=e.supplementary_metadata || jsonb_build_object(
             'duplicateClassification','represented_by_parent_event',
             'representedByAccountingEventId',owners.parent_event_id
           )
      from owners
     where e.id=owners.redundant_event_id
       and e.processing_status not in ('posted','reversed','ignored_duplicate');

    do $$
    begin
      if exists (
        select 1
          from accounting_events e
          join orders o on o.id=e.source_entity_id and o.company_id=e.company_id
         where e.source_entity_type='order'
           and e.event_type='order_delivered'
           and e.journal_id is null
           and e.processing_status in ('failed','blocked_configuration','retry_pending')
           and o.customer_amount_due=0 and o.trader_net_payable=0
      ) then
        raise exception using errcode='23514', message='zero_value_order_event_not_classified';
      end if;
      if exists (
        select 1
          from accounting_events e
          join cash_bank_movements m
            on m.id=e.source_entity_id and m.company_id=e.company_id
         where e.source_entity_type='general_expense_payment'
           and e.event_type in ('cash_withdrawal_confirmed','bank_withdrawal_confirmed')
           and e.journal_id is null
           and m.idempotency_identity like 'general_expense_payment:%'
           and e.processing_status<>'ignored_duplicate'
      ) then
        raise exception using errcode='23514', message='general_expense_duplicate_event_not_classified';
      end if;
    end
    $$;
  `.execute(database);
}

export async function down(database: Kysely<MigrationDatabase>): Promise<void> {
  await sql`
    update cash_bank_movements movement
       set accounting_event_id=null,
           updated_at=now()
      from accounting_events redundant
     where redundant.company_id=movement.company_id
       and redundant.source_entity_id=movement.id
       and redundant.supplementary_metadata->>'duplicateClassification'='represented_by_parent_event'
       and movement.accounting_event_id=(redundant.supplementary_metadata->>'representedByAccountingEventId')::uuid;

    update accounting_events
       set processing_status='failed',
           processed_at=null,
           supplementary_metadata=supplementary_metadata
             - 'terminalClassification'
             - 'classificationReason'
     where processing_status='ignored_no_accounting_required';

    update accounting_events
       set processing_status='received',
           processed_at=null,
           supplementary_metadata=supplementary_metadata
             - 'duplicateClassification'
             - 'representedByAccountingEventId'
     where processing_status='ignored_duplicate'
       and supplementary_metadata->>'duplicateClassification'='represented_by_parent_event'
       and source_entity_type='general_expense_payment';

    alter table accounting_events drop constraint accounting_events_status_check;
    alter table accounting_events add constraint accounting_events_status_check check (
      processing_status in (
        'received','processing','validated','posted','failed','retry_pending',
        'blocked_configuration','reversed','ignored_duplicate'
      )
    );
  `.execute(database);
}
