// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { DemoRequestPage } from './DemoRequestPage';

afterEach(()=>{cleanup();sessionStorage.clear();localStorage.clear();window.__TAWSEELHUB_ANALYTICS_EVENTS__=[];vi.restoreAllMocks();vi.unstubAllGlobals();});
function completeRequiredFields(){fireEvent.change(screen.getByLabelText('Company Name *'),{target:{value:'Atlas Delivery'}});fireEvent.change(screen.getByLabelText('Contact Person *'),{target:{value:'Amina Noor'}});fireEvent.change(screen.getByLabelText('Mobile Number *'),{target:{value:'0501234567'}});fireEvent.change(screen.getByLabelText('Email *'),{target:{value:'amina@example.ae'}});fireEvent.change(screen.getByLabelText('Country *'),{target:{value:'Saudi Arabia'}});fireEvent.change(screen.getByLabelText('Preferred Contact Method *'),{target:{value:'email'}});fireEvent.click(screen.getByLabelText(/I agree that Tawseelhub/));}
describe('demo qualification form',()=>{it('preserves values and shows validation feedback without conversion',()=>{render(<DemoRequestPage/>);fireEvent.change(screen.getByLabelText('Company Name *'),{target:{value:'Atlas Delivery'}});fireEvent.click(screen.getByRole('button',{name:'Request Demo'}));expect(screen.getByLabelText('Company Name *')).toHaveValue('Atlas Delivery');expect(screen.getByText('Please enter your contact name.')).toBeInTheDocument();expect(screen.getByText('Please enter a valid mobile number.')).toBeInTheDocument();expect(JSON.stringify(window.__TAWSEELHUB_ANALYTICS_EVENTS__)).not.toContain('demo_request_submitted');});it('shows the success reference after submission and emits one safe conversion',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({id:'lead-1',referenceNumber:'DEMO-000123'})}));render(<DemoRequestPage/>);completeRequiredFields();fireEvent.click(screen.getByRole('button',{name:'Request Demo'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Thank You'})).toBeInTheDocument());expect(screen.getByText('Reference: DEMO-000123')).toBeInTheDocument();const events=window.__TAWSEELHUB_ANALYTICS_EVENTS__ as Array<Record<string,unknown>>;const conversions=events.filter((event)=>event.event==='demo_request_submitted');expect(conversions).toHaveLength(1);expect(conversions[0]).toMatchObject({reference:'DEMO-000123',lead_type:'delivery_company'});expect(JSON.stringify(conversions[0])).not.toMatch(/Amina|amina@example|0501234567|mobile_number|email_address|contact_person/i);});it('shows a friendly server error and retains the form without conversion',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:400,headers:new Headers({'content-type':'application/json'}),json:async()=>({error:{message:'Please review your request.'}})}));render(<DemoRequestPage/>);completeRequiredFields();fireEvent.click(screen.getByRole('button',{name:'Request Demo'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Please review your request.'));expect(screen.getByLabelText('Company Name *')).toHaveValue('Atlas Delivery');expect(JSON.stringify(window.__TAWSEELHUB_ANALYTICS_EVENTS__)).not.toContain('demo_request_submitted');});});
