export const pricingPlans = [
  {
    name: 'Free',
    price: 'AED 0',
    period: 'per month',
    volume: 'Up to 100 orders / month',
    volumeAr: 'حتى 100 طلب / شهر',
    cta: 'Start with a demo',
    ctaAr: 'ابدأ بعرض',
    href: '/request-demo',
    highlights: ['Order and driver operations foundation', 'COD and settlement visibility', 'Reports for early-stage teams'],
    highlightsAr: ['أساسيات إدارة الطلبات والسائقين', 'وضوح التحصيل عند الاستلام والتسويات', 'تقارير للفرق في بداياتها'],
  },
  {
    name: 'Starter',
    price: 'AED 500',
    period: 'per month',
    volume: '100–2,000 orders / month',
    volumeAr: '100–2,000 طلب / شهر',
    cta: 'Request Demo',
    ctaAr: 'اطلب عرضاً',
    href: '/request-demo',
    highlights: ['Daily order management', 'Driver assignment workflows', 'COD collection controls'],
    highlightsAr: ['إدارة الطلبات اليومية', 'مسارات إسناد السائقين', 'ضوابط التحصيل عند الاستلام'],
  },
  {
    name: 'Growth',
    price: 'AED 1000',
    period: 'per month',
    volume: '2,001–5,000 orders / month',
    volumeAr: '2,001–5,000 طلب / شهر',
    cta: 'Request Demo',
    ctaAr: 'اطلب عرضاً',
    href: '/request-demo',
    highlights: ['Trader relationship tracking', 'Trader settlement workflows', 'Operational reporting'],
    highlightsAr: ['متابعة علاقات التجار', 'مسارات تسويات التجار', 'تقارير تشغيلية'],
  },
  {
    name: 'Business',
    price: 'AED 2000',
    period: 'per month',
    volume: '5,001–10,000 orders / month',
    volumeAr: '5,001–10,000 طلب / شهر',
    cta: 'Request Demo',
    ctaAr: 'اطلب عرضاً',
    href: '/request-demo',
    highlights: ['Accounting and payroll support', 'Management reporting', 'Platform controls for growing teams'],
    highlightsAr: ['دعم المحاسبة والرواتب', 'تقارير للإدارة', 'ضوابط منصة للفرق النامية'],
  },
] as const;

export const pricingGapNote = 'For more than 10,000 monthly orders, Tawseelhub can confirm a custom commercial tier.';
