import {
  IsBoolean,
  IsIn,
  IsNumberString,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  MaxLength,
} from "class-validator";

export const whatsappMessageLanguages = ["both", "ar", "en"] as const;
export type WhatsAppMessageLanguage = (typeof whatsappMessageLanguages)[number];

export const whatsappDestinationTypes = ["group"] as const;
export type WhatsAppDestinationType = (typeof whatsappDestinationTypes)[number];

export class UpdateTraderWhatsAppSettingsDto {
  @IsBoolean()
  public readonly notificationsEnabled!: boolean;

  // Only `group` exists today; the closed @IsIn (and the matching database
  // CHECK) is what a later prompt widens when new destination types are
  // approved.
  @IsOptional()
  @IsIn(whatsappDestinationTypes)
  public readonly destinationType?: WhatsAppDestinationType;

  // The provider's internal chat id (e.g. `1203...@g.us`) — opaque and
  // provider-issued, so bounded generously rather than pattern-matched.
  @IsOptional()
  @IsString()
  @Length(1, 256)
  public readonly providerGroupId?: string;

  // Display/audit snapshot only — never used as the group's identity.
  @IsOptional()
  @IsString()
  @MaxLength(512)
  public readonly groupNameSnapshot?: string;

  @IsOptional()
  @IsIn(whatsappMessageLanguages)
  public readonly messageLanguage?: WhatsAppMessageLanguage;
}

/**
 * The public connection view. Deliberately EXCLUDES
 * `encrypted_session_state` and `provider_account_reference` — session and
 * provider account material is credential-grade and never leaves the backend
 * through any API response.
 *
 * `qr` is the ONLY pairing artifact that ever reaches the frontend: the
 * current QR payload string, present exclusively while the status is
 * `waiting_for_qr_scan`, tenant-scoped, held in server memory only, and
 * rotating on the provider's own schedule (the frontend just re-polls this
 * endpoint and re-renders). It must never be written to browser storage.
 */
export interface CompanyWhatsAppConnectionView {
  readonly status: string;
  /** True when Platform Administration has switched WhatsApp off for this
   *  Company — the UI shows why every WhatsApp action is unavailable. */
  readonly platformDisabled: boolean;
  readonly providerType: string;
  readonly connectedPhoneNumber: string | null;
  readonly connectedAt: Date | null;
  readonly lastConnectedAt: Date | null;
  readonly lastDisconnectedAt: Date | null;
  readonly disconnectReason: string | null;
  readonly lastHealthCheckAt: Date | null;
  readonly requiresQrScan: boolean;
  readonly qrAvailable: boolean;
  readonly qr: string | null;
}

export interface WhatsAppGroupView {
  /** The provider's internal group id (e.g. `1203...@g.us`) — the group's
   *  authoritative identity. The name is display data only. */
  readonly id: string;
  readonly name: string;
  readonly participantCount?: number;
}

export interface TraderWhatsAppSettingsView {
  readonly traderId: string;
  readonly configured: boolean;
  readonly notificationsEnabled: boolean;
  readonly destinationType: WhatsAppDestinationType;
  readonly providerGroupId: string | null;
  readonly groupNameSnapshot: string | null;
  readonly messageLanguage: WhatsAppMessageLanguage;
  readonly configuredAt: Date | null;
}

export class SendTestMessageDto {
  // One id per deliberate click, generated by the frontend: a retried or
  // double-submitted request for the SAME click collapses onto one message,
  // while a new click (new id) is a new message by design.
  @IsOptional()
  @IsString()
  @Length(8, 64)
  public readonly clientRequestId?: string;
}

export interface WhatsAppTestMessageResult {
  readonly messageId: string;
  readonly status: string;
  readonly providerMessageId: string | null;
  readonly failureCode: string | null;
  /** True when this request matched an already-recorded click and no new
   *  message was sent. */
  readonly duplicate?: boolean;
}

export const whatsappMessageStatuses = [
  "pending",
  "processing",
  "sent",
  "failed",
  "requires_review",
  "cancelled",
] as const;

export class ListWhatsAppMessagesDto {
  @IsOptional()
  @IsIn(whatsappMessageStatuses)
  public readonly status?: (typeof whatsappMessageStatuses)[number];

  @IsOptional()
  @IsIn(["order_status", "test"])
  public readonly messageType?: "order_status" | "test";

  @IsOptional()
  @IsUUID()
  public readonly traderId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(64)
  public readonly orderNumber?: string;

  /** ISO dates; validated loosely here, parsed defensively in the service. */
  @IsOptional()
  @IsString()
  @MaxLength(32)
  public readonly dateFrom?: string;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  public readonly dateTo?: string;

  @IsOptional()
  @IsNumberString()
  public readonly page?: string;

  @IsOptional()
  @IsNumberString()
  public readonly pageSize?: string;
}

export class RetryWhatsAppMessageDto {
  /** Required (true) for `requires_review` rows: the caller explicitly
   *  accepts that the Trader group may receive a duplicate message. */
  @IsOptional()
  @IsBoolean()
  public readonly confirmDuplicateRisk?: boolean;
}

export class ResolveWhatsAppMessageDto {
  @IsIn(["mark_resolved", "cancel"])
  public readonly action!: "mark_resolved" | "cancel";
}

export interface WhatsAppMessageListItemView {
  readonly id: string;
  readonly createdAt: Date;
  readonly traderId: string;
  readonly traderName: string | null;
  readonly orderId: string | null;
  readonly orderNumber: string | null;
  readonly orderStatus: string | null;
  readonly groupNameSnapshot: string | null;
  readonly messageType: string;
  readonly messageLanguage: string;
  readonly status: string;
  readonly attemptCount: number;
  readonly failureCode: string | null;
  readonly nextAttemptAt: Date | null;
  readonly sentAt: Date | null;
}

export interface WhatsAppMessageAttemptView {
  readonly attemptNumber: number;
  readonly startedAt: Date;
  readonly completedAt: Date | null;
  readonly result: string | null;
  readonly failureClassification: string | null;
  readonly providerResponseSummary: string | null;
}

export interface WhatsAppMessageDetailView extends WhatsAppMessageListItemView {
  readonly orderStatusHistoryId: string | null;
  readonly statusEventOccurredAt: Date | null;
  readonly providerGroupId: string;
  readonly messageBody: string;
  readonly providerMessageId: string | null;
  readonly queuedAt: Date;
  readonly processingAt: Date | null;
  readonly failedAt: Date | null;
  readonly failureReason: string | null;
  readonly attempts: readonly WhatsAppMessageAttemptView[];
}

export interface WhatsAppMessagePage {
  readonly items: readonly WhatsAppMessageListItemView[];
  readonly page: number;
  readonly pageSize: number;
  readonly total: number;
}

export interface TraderGroupHealthRow {
  readonly traderId: string;
  readonly traderName: string;
  readonly groupNameSnapshot: string | null;
  readonly providerGroupId: string;
  readonly notificationsEnabled: boolean;
  /** true/false when live discovery ran; null when WhatsApp is not connected
   *  and availability is unknowable right now. */
  readonly available: boolean | null;
}

export interface TraderGroupHealthView {
  readonly connected: boolean;
  readonly checkedAt: Date | null;
  readonly configured: number;
  readonly availableCount: number;
  readonly needsAttention: number;
  readonly rows: readonly TraderGroupHealthRow[];
}

/** Company-level operational counts for the Configuration → WhatsApp page:
 *  is the Trader notification pipeline healthy? */
export interface WhatsAppMessageSummaryView {
  readonly pending: number;
  readonly processing: number;
  readonly failed: number;
  readonly requiresReview: number;
  readonly sentToday: number;
  readonly sentLast24h: number;
  readonly oldestPendingAt: Date | null;
  readonly lastSuccessfulSendAt: Date | null;
}

export interface WhatsAppNotificationView {
  readonly id: string;
  readonly traderId: string;
  readonly messageType: string;
  readonly orderId: string | null;
  readonly orderStatusHistoryId: string | null;
  readonly orderNumber: string | null;
  readonly orderStatus: string | null;
  readonly destinationType: string;
  readonly providerGroupId: string;
  readonly groupNameSnapshot: string | null;
  readonly messageLanguage: string;
  readonly messageBody: string;
  readonly status: string;
  readonly providerMessageId: string | null;
  readonly queuedAt: Date;
  readonly sentAt: Date | null;
  readonly failedAt: Date | null;
  readonly failureCode: string | null;
  readonly failureReason: string | null;
  readonly attemptCount: number;
  readonly createdAt: Date;
}
