import { useEffect, useState, type ReactElement } from "react";
import { platformApi, type WorkflowTestCompany, type WorkflowTestRun } from "../api/platform-client.js";

export function AutomatedWorkflowTestingPage():ReactElement {
  const [companies,setCompanies]=useState<readonly WorkflowTestCompany[]>([]),[runs,setRuns]=useState<readonly WorkflowTestRun[]>([]);
  const [companyId,setCompanyId]=useState(""),[mode,setMode]=useState<"full"|"smoke">("full"),[orders,setOrders]=useState(20),[days,setDays]=useState(1),[concurrency,setConcurrency]=useState(1),[error,setError]=useState("");
  const load=()=>Promise.all([platformApi.workflowTestCompanies(),platformApi.workflowTestRuns()]).then(([c,r])=>{setCompanies(c);setRuns(r);if(!companyId)setCompanyId(c[0]?.id??"");});
  useEffect(()=>{void load().catch(()=>setError("Workflow testing data could not be loaded."));},[]);
  useEffect(()=>{if(!runs.some(run=>["scheduled","running","stopping"].includes(run.status)))return;const timer=window.setInterval(()=>void load().catch(()=>undefined),3000);return()=>window.clearInterval(timer);},[runs]);
  const message=(caught:unknown,fallback:string)=>caught instanceof Error&&caught.message.trim()?caught.message:fallback;
  async function create(){setError("");try{await platformApi.createWorkflowTestRun({companyId,mode,ordersPerDay:orders,durationDays:days,concurrency,sideEffectsSuppressed:true,configuration:{channels:["company_portal","trader_portal","store","quote","commerce"],languages:["en","ar"],viewports:["desktop","tablet","mobile_web"]}});await load();}catch(caught){setError(message(caught,"The workflow test could not be created."));}}
  async function enable(){const company=companies.find(item=>item.id===companyId);if(!company)return;const confirmation=window.prompt(`Type ENABLE ${company.code} to mark this non-production Company for destructive workflow testing.`);if(confirmation===null)return;setError("");try{await platformApi.enableWorkflowTestingCompany(company.id,confirmation.trim());await load();}catch(caught){setError(message(caught,"The Company could not be enabled."));}}
  async function mutate(run:WorkflowTestRun,action:"start"|"pause"|"resume"|"stop"|"cancel"){setError("");try{await platformApi.mutateWorkflowTestRun(run.id,action,run.version);await load();}catch(caught){setError(message(caught,"The workflow test status could not be changed."));}}
  async function connect(run:WorkflowTestRun){setError("");try{await platformApi.connectRecentWorkflowTestOrders(run.id,run.version);await load();}catch(caught){setError(message(caught,"Recent test orders could not be connected."));}}
  return <section className="platform-panel">
    <div className="platform-panel__header"><div><h2>Automated Workflow Testing</h2><p className="platform-muted">Operates Tawseelhub’s real screens like a user. Full tests are restricted to explicitly enabled test Companies; Dana is blocked.</p></div></div>{error&&<p role="alert">{error}</p>}
    <div className="platform-filters">
      <label className="platform-field"><span>Company</span><select value={companyId} onChange={event=>setCompanyId(event.target.value)}><option value="">Select…</option>{companies.map(company=><option key={company.id} value={company.id}>{company.name} · {company.environment}{company.enabled?" · Enabled":" · Not enabled"}</option>)}</select></label>
      <label className="platform-field"><span>Mode</span><select value={mode} onChange={event=>setMode(event.target.value as "full"|"smoke")}><option value="full">Full Workflow Test</option><option value="smoke">Safe Smoke Test</option></select></label>
      <label className="platform-field"><span>Orders per day</span><input min="1" max={mode==="smoke"?5:1000} type="number" value={orders} onChange={event=>setOrders(Number(event.target.value))}/></label>
      <label className="platform-field"><span>Days</span><input min="1" max="30" type="number" value={days} onChange={event=>setDays(Number(event.target.value))}/></label>
      <label className="platform-field"><span>Browser workers</span><input min="1" max="10" type="number" value={concurrency} onChange={event=>setConcurrency(Number(event.target.value))}/></label>
    </div>
    <p><strong>Planned total:</strong> {orders*days} Orders</p><p className="platform-muted">External notifications, payments and production provider writes: suppressed for Full Workflow tests.</p>
    <div className="publishing-actions"><button type="button" disabled={!companyId||companies.find(company=>company.id===companyId)?.enabled===true} onClick={()=>void enable()}>Enable selected test Company</button><button className="platform-button" disabled={!companyId} onClick={()=>void create()}>Create test plan</button></div>
    <h3>Runs</h3><div className="platform-table-scroll"><table className="platform-table"><thead><tr><th>Company</th><th>Mode</th><th>Status</th><th>Planned</th><th>Progress</th><th>Failure details</th><th>Controls</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td>{run.companyName}</td><td>{run.mode}</td><td>{run.status}</td><td>{run.planned_orders}</td><td>{run.progress?.linked??0} orders linked · {run.progress?.completed??0} completed · {run.progress?.failed??0} failed</td><td>{run.failureReasons?.[0]??"—"}</td><td>{run.status==="draft"&&<><button onClick={()=>void connect(run)}>Connect recent orders</button><button onClick={()=>void mutate(run,"start")}>Start</button><button onClick={()=>void mutate(run,"cancel")}>Cancel</button></>}{run.status==="running"&&<button onClick={()=>void mutate(run,"pause")}>Pause</button>}{run.status==="paused"&&<button onClick={()=>void mutate(run,"resume")}>Resume</button>}{["scheduled","running","paused"].includes(run.status)&&<button onClick={()=>void mutate(run,"stop")}>Stop</button>}</td></tr>)}</tbody></table></div>
  </section>;
}
