/* eslint-disable @typescript-eslint/no-explicit-any -- CMS responses are legacy ungenerated Platform API records */
import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { platformApi } from "../api/platform-client.js";

const empty = { internalTitle:"",title:"",slug:"",language:"en",translationGroupId:"",summary:"",contentHtml:"",authorName:"Tawseelhub Team",primaryTopic:"",featuredImagePublicUrl:"",featuredImageAlt:"",robotsIndex:true,robotsFollow:true,includeInSitemap:true,showInMainNavigation:false,showInResources:false,canonicalUrl:"",seoTitle:"",metaDescription:"",socialTitle:"",socialDescription:"",socialImageUrl:"",socialImageAlt:"" };
type FormState = typeof empty;
const fromRow = (row:any):FormState => ({...empty,internalTitle:row.internal_title??"",title:row.title??"",slug:row.slug??"",language:row.language??"en",translationGroupId:row.translation_group_id??"",summary:row.summary??"",contentHtml:(row.content??[]).map((block:any)=>block.type==="html"?block.text:`<${block.type==="paragraph"?"p":block.type}>${block.text??""}</${block.type==="paragraph"?"p":block.type}>`).join("\n"),authorName:row.author_name??"",primaryTopic:row.primary_topic??"",featuredImagePublicUrl:row.featured_image_public_url??"",featuredImageAlt:row.featured_image_alt??"",robotsIndex:row.robots_index!==false,robotsFollow:row.robots_follow!==false,includeInSitemap:row.include_in_sitemap!==false,showInMainNavigation:Boolean(row.show_in_main_navigation),showInResources:Boolean(row.show_in_resources),canonicalUrl:row.canonical_url??"",seoTitle:row.seo_title??"",metaDescription:row.meta_description??"",socialTitle:row.social_title??"",socialDescription:row.social_description??"",socialImageUrl:row.social_image_url??"",socialImageAlt:row.social_image_alt??""});
const payload = (form:FormState) => ({...form,translationGroupId:form.translationGroupId||undefined,content:[{type:"html",text:form.contentHtml}],authorName:form.authorName||undefined,primaryTopic:form.primaryTopic||undefined,featuredImagePublicUrl:form.featuredImagePublicUrl||undefined,featuredImageAlt:form.featuredImageAlt||undefined,canonicalUrl:form.canonicalUrl||undefined,seoTitle:form.seoTitle||undefined,metaDescription:form.metaDescription||undefined,socialTitle:form.socialTitle||undefined,socialDescription:form.socialDescription||undefined,socialImageUrl:form.socialImageUrl||undefined,socialImageAlt:form.socialImageAlt||undefined,contentHtml:undefined});

export function SeoGuidesPage() {
  const { id }=useParams(),navigate=useNavigate();
  const [items,setItems]=useState<any[]>([]),[detail,setDetail]=useState<any>(),[form,setForm]=useState<FormState>(empty),[message,setMessage]=useState(""),[readiness,setReadiness]=useState<any>();
  const load=async()=>{setItems(await platformApi.seoGuides());if(id&&id!=="new"){const row=await platformApi.seoGuide(id);setDetail(row);setForm(fromRow(row));setReadiness(await platformApi.seoGuideReadiness(id));}else{setDetail(undefined);setForm(empty);setReadiness(undefined);}};
  useEffect(()=>{void load().catch((error:Error)=>setMessage(error.message));},[id]);
  const set=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm((current)=>({...current,[key]:value}));
  const save=async(event:FormEvent)=>{event.preventDefault();setMessage("Saving…");try{const row=id&&id!=="new"?await platformApi.updateSeoGuide(id,payload(form)):await platformApi.createSeoGuide(payload(form));setMessage("SEO Guide draft saved.");if(!id||id==="new")navigate(`/website/seo-guides/${row.id}`,{replace:true});else await load();}catch(error){setMessage(error instanceof Error?error.message:"Save failed");}};
  const changeStatus=async(status:string)=>{if(!id||id==="new")return;const scheduledAt=status==="scheduled"?globalThis.prompt("Schedule date/time (ISO format)")??undefined:undefined;await platformApi.updateSeoGuideStatus(id,{status,scheduledAt});setMessage(`Guide ${status}.`);await load();};
  return <section className="platform-page">
    <header className="platform-page__header"><div><p className="platform-eyebrow">Website</p><h1>SEO Guides</h1><p className="platform-muted">Public, indexable long-form pages outside the Blog. They are not added to navigation or listings unless explicitly enabled.</p></div><Link className="platform-button" to="/website/seo-guides/new">New SEO Guide</Link></header>
    {message&&<p role="status">{message}</p>}
    <div className="platform-grid platform-grid--two">
      <aside className="platform-card"><h2>Guides</h2>{items.length===0?<p>No Guides yet.</p>:<ul>{items.map((item)=><li key={item.id}><Link to={`/website/seo-guides/${item.id}`}>{item.internal_title}</Link> <small>{item.language.toUpperCase()} · {item.status}</small></li>)}</ul>}</aside>
      {(id||items.length===0)&&<form className="platform-card platform-form" onSubmit={save}>
        <h2>{id&&id!=="new"?"Edit Guide":"Create Guide"}</h2>
        <label>Internal title<input required value={form.internalTitle} onChange={e=>set("internalTitle",e.target.value)}/></label>
        <label>Public page title / H1<input required value={form.title} onChange={e=>set("title",e.target.value)}/></label>
        <div className="platform-form__row"><label>Language<select value={form.language} onChange={e=>set("language",e.target.value)}><option value="en">English</option><option value="ar">Arabic</option></select></label><label>Slug<input required dir="ltr" value={form.slug} onChange={e=>set("slug",e.target.value)}/></label></div>
        <label>Translation group ID <small>(use the same ID for the EN and AR versions)</small><input dir="ltr" value={form.translationGroupId} onChange={e=>set("translationGroupId",e.target.value)}/></label>
        <label>Short summary<textarea required value={form.summary} onChange={e=>set("summary",e.target.value)}/></label>
        <label>Body HTML<textarea rows={16} value={form.contentHtml} onChange={e=>set("contentHtml",e.target.value)}/></label>
        <div className="platform-form__row"><label>Author<input value={form.authorName} onChange={e=>set("authorName",e.target.value)}/></label><label>Primary topic<input value={form.primaryTopic} onChange={e=>set("primaryTopic",e.target.value)}/></label></div>
        <label>Featured image URL<input dir="ltr" value={form.featuredImagePublicUrl} onChange={e=>set("featuredImagePublicUrl",e.target.value)}/></label><label>Featured image alt text<input value={form.featuredImageAlt} onChange={e=>set("featuredImageAlt",e.target.value)}/></label>
        <h3>SEO and social</h3><label>Canonical URL<input dir="ltr" placeholder={`https://tawseelhub.com/${form.language==="ar"?"ar/":""}guides/${form.slug}`} value={form.canonicalUrl} onChange={e=>set("canonicalUrl",e.target.value)}/></label><label>SEO title<input value={form.seoTitle} onChange={e=>set("seoTitle",e.target.value)}/></label><label>Meta description<textarea value={form.metaDescription} onChange={e=>set("metaDescription",e.target.value)}/></label><label>Social title<input value={form.socialTitle} onChange={e=>set("socialTitle",e.target.value)}/></label><label>Social description<textarea value={form.socialDescription} onChange={e=>set("socialDescription",e.target.value)}/></label><label>Social image URL<input dir="ltr" value={form.socialImageUrl} onChange={e=>set("socialImageUrl",e.target.value)}/></label><label>Social image alt<input value={form.socialImageAlt} onChange={e=>set("socialImageAlt",e.target.value)}/></label>
        <div className="platform-checks"><label><input type="checkbox" checked={form.robotsIndex} onChange={e=>set("robotsIndex",e.target.checked)}/> Allow indexing</label><label><input type="checkbox" checked={form.robotsFollow} onChange={e=>set("robotsFollow",e.target.checked)}/> Follow links</label><label><input type="checkbox" checked={form.includeInSitemap} onChange={e=>set("includeInSitemap",e.target.checked)}/> Show in sitemap</label><label><input type="checkbox" checked={form.showInMainNavigation} onChange={e=>set("showInMainNavigation",e.target.checked)}/> Show in main navigation</label><label><input type="checkbox" checked={form.showInResources} onChange={e=>set("showInResources",e.target.checked)}/> Show in Resources</label></div>
        <button className="platform-button" type="submit">Save draft</button>
        {id&&id!=="new"&&<><div className="platform-actions"><button type="button" onClick={()=>void changeStatus("published")}>Publish</button><button type="button" onClick={()=>void changeStatus("scheduled")}>Schedule</button><button type="button" onClick={()=>void changeStatus("unpublished")}>Unpublish</button><button type="button" onClick={()=>void changeStatus("archived")}>Archive</button><a href={`${form.language==="ar"?"/ar":""}/guides/${form.slug}`} target="_blank" rel="noreferrer">Open public URL</a></div>
        <section><h3>Private consultant source documents</h3><p>PDF or DOCX, maximum 15 MB. Every upload creates a new immutable revision.</p><input accept=".pdf,.docx" type="file" onChange={e=>{const file=e.target.files?.[0];if(file)void platformApi.uploadSeoGuideSource(id,file).then(load).then(()=>setMessage("Source revision uploaded privately.")).catch((error:Error)=>setMessage(error.message));}}/>{detail?.sources?.map((source:any)=><p key={source.id}>v{source.revision} · {source.original_filename} · <a href={platformApi.seoGuideSourceDownloadUrl(id,source.id)}>Download</a></p>)}</section>
        {readiness&&<section><h3>SEO readiness: {readiness.status}</h3><ul>{readiness.checks.map((check:any)=><li key={check.key}>{check.pass?"✓":"⚠"} {check.message}</li>)}</ul>{readiness.overlapCandidates?.length?<p>Possible overlapping Guide: {readiness.overlapCandidates.map((x:any)=>x.title).join(", ")}</p>:null}</section>}</>}
      </form>}
    </div>
  </section>;
}
