/**
 * Arabic interface copy.
 *
 * ---------------------------------------------------------------------------
 * WHAT IS TRANSLATED AND WHAT IS NOT
 * ---------------------------------------------------------------------------
 *
 * Everything here is a SYSTEM label — text this application owns. All of it is
 * translated, because an Arabic page that leaves "Featured stores" or "Product
 * code" in English is not an Arabic page; it is an English page with the
 * columns flipped.
 *
 * Trader-entered content is the opposite case and is never touched: a Product
 * called "Dev Embroidered Abaya" stays exactly that in Arabic, because the
 * Trader has not written an Arabic name and inventing one would put words in a
 * merchant's mouth about their own goods. When per-language Trader fields
 * arrive, they get used here; machine translation does not.
 *
 * Wording follows Gulf retail convention rather than literal translation —
 * "متوفر" for in-stock, "مطلوب" for a required option, "السعر السابق" for a
 * struck-through price — because these are the words a shopper in the UAE
 * already reads on other shopping sites.
 */
export const ar = {
  auth: {
    account: {
      addAddress: "إضافة عنوان",
      addressDefault: "افتراضي",
      addresses: "العناوين",
      addressesEmpty: "لا توجد عناوين محفوظة بعد.",
      businessInfo: "معلومات الحساب",
      delete: "حذف",
      edit: "تعديل",
      email: "البريد الإلكتروني",
      logout: "تسجيل الخروج",
      mobile: "رقم الجوال",
      myOrders: "طلباتي",
      name: "الاسم",
      preferredLanguage: "اللغة المفضلة",
      profile: "الملف الشخصي",
      save: "حفظ",
      saved: "تم الحفظ.",
      setDefault: "تعيين كافتراضي",
      title: "حسابي",
    },
    address: {
      area: "المنطقة",
      deliveryInstructions: "تعليمات التوصيل",
      emirate: "الإمارة",
      label: "التسمية",
      locationLink: "رابط الموقع",
      mobile: "رقم الجوال",
      recipientName: "اسم المستلم",
      street: "العنوان",
    },
    completeReset: "إعادة تعيين كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    createAccount: "إنشاء حساب",
    email: "البريد الإلكتروني",
    errors: {
      customer_already_registered: "يوجد حساب بهذا الرقم أو البريد الإلكتروني بالفعل.",
      invalid_credentials: "رقم الجوال/البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      invalid_mobile: "أدخل رقم جوال إماراتي صالحًا.",
      network_error: "تعذّر الوصول إلى الخادم. حاول مرة أخرى.",
      passwordMismatch: "كلمتا المرور غير متطابقتين.",
      password_reset_token_invalid: "رابط إعادة التعيين غير صالح أو منتهي الصلاحية.",
      store_order_not_found: "لم نتمكن من العثور على هذا الطلب.",
      store_order_tracking_failed: "تعذّر التحقق من هذا الطلب بالمعلومات المُدخلة.",
      unknown_error: "حدث خطأ ما. حاول مرة أخرى.",
    },
    forgotPassword: "هل نسيت كلمة المرور؟",
    forgotPasswordLead: "أدخل رقم جوالك أو بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.",
    forgotPasswordTitle: "إعادة تعيين كلمة المرور",
    haveAccount: "هل لديك حساب بالفعل؟",
    identifier: "رقم الجوال أو البريد الإلكتروني",
    login: "تسجيل الدخول",
    loginTitle: "تسجيل الدخول إلى حسابك",
    logout: "تسجيل الخروج",
    mobile: "رقم الجوال",
    name: "الاسم",
    newAccount: "إنشاء حساب",
    newPassword: "كلمة المرور الجديدة",
    noAccount: "ليس لديك حساب؟",
    password: "كلمة المرور",
    register: "التسجيل",
    registerLead: "أنشئ حسابك لتبدأ التسوق.",
    registerTitle: "إنشاء حسابك",
    resetLead: "اختر كلمة مرور جديدة لحسابك.",
    resetLinkSent: "إذا كان هناك حساب بهذا الرقم أو البريد الإلكتروني، فقد تم إرسال رابط إعادة التعيين.",
    resetSuccess: "تمت إعادة تعيين كلمة المرور. يمكنك الآن تسجيل الدخول.",
    resetToken: "رمز إعادة التعيين",
    submitReset: "إرسال رابط إعادة التعيين",
    termsAcceptance: "أوافق على شروط الخدمة وسياسة الخصوصية",
  },
  categories: {
    breadcrumb: "مسار التنقل",
    browseOthers: "تصفّح فئات أخرى",
    empty: {
      body: "ستظهر الفئات هنا بمجرد إعداد السوق.",
      title: "لا توجد فئات بعد",
    },
    home: "الرئيسية",
    noProducts: {
      body: "لا توجد منتجات مدرجة في هذه الفئة بعد.",
      title: "لا توجد منتجات بعد",
    },
    noStores: {
      body: "لا توجد متاجر مدرجة في هذه الفئة بعد.",
      title: "لا توجد متاجر بعد",
    },
    notFound: {
      body: "لم نتمكن من العثور على هذه الفئة.",
      title: "الفئة غير موجودة",
    },
    productCount: "منتج واحد",
    productCount_other: "{{count}} منتجات",
    products: "المنتجات",
    stores: "المتاجر",
    subcategories: "الفئات الفرعية",
    title: "الفئات",
    viewAll: "عرض الكل",
  },
  common: {
    account: "حسابي",
    all: "الكل",
    arabic: "العربية",
    back: "رجوع",
    cart: "السلة",
    comingSoon: "قريبًا",
    english: "English",
    language: "اللغة",
    loading: "جارٍ التحميل",
    offlineBanner: "أنت غير متصل بالإنترنت. قد تكون بعض ميزات المتجر غير متاحة.",
    retry: "إعادة المحاولة",
    search: "بحث",
    searchPlaceholder: "ابحث عن المتاجر والمنتجات",
    skipToContent: "تخطٍ إلى المحتوى",
    viewAll: "عرض الكل",
  },
  errors: {
    apiUnavailable: {
      body: "تعذّر الوصول إلى خدمة المتجر. يرجى المحاولة بعد قليل.",
      title: "الخدمة غير متاحة",
    },
    network: {
      body: "تحقّق من الاتصال ثم أعد المحاولة.",
      title: "مشكلة في الاتصال",
    },
    productNotFound: {
      body: "لم يعد هذا المنتج مدرجًا.",
      title: "المنتج غير موجود",
    },
    storeClosed: {
      body: "هذا المتجر مغلق مؤقتًا ولا يستقبل الطلبات حاليًا.",
      title: "مغلق مؤقتًا",
    },
    storeNotFound: {
      body: "لم نتمكن من العثور على متجر على هذا العنوان.",
      title: "المتجر غير موجود",
    },
  },
  footer: {
    company: "بلولاين جي بي تي",
    customer: "للعملاء",
    legal: "الشؤون القانونية",
    privacy: "الخصوصية",
    rights: "متجر بلولاين جي بي تي",
    support: "الدعم",
    tagline: "تسوّق من المتاجر المحلية في الإمارات وادفع نقدًا عند الاستلام.",
    terms: "الشروط",
    track: "تتبّع طلبك",
  },
  home: {
    account: {
      body: "سجّل الدخول لإدارة ملفك الشخصي وعناوينك. سيتوفر سجل الطلبات مع طلبات المتجر.",
      title: "حسابك",
    },
    app: {
      body: "تطبيق متجر بلولاين جي بي تي في الطريق.",
      title: "تسوّق أينما كنت",
    },
    bestsellers: { title: "الأكثر مبيعًا" },
    curatedCollections: { title: "تشكيلات مختارة" },
    empty: {
      body: "لا توجد متاجر منشورة بعد. سيظهر المتجر هنا فور افتتاحه.",
      title: "لا يوجد ما نعرضه بعد",
    },
    featuredStores: {
      subtitle: "متاجر مفتوحة الآن على بلولاين جي بي تي",
      title: "متاجر مميّزة",
    },
    hero: {
      cta: "تصفّح الفئات",
      lead: "تسوّق من المتاجر المحلية في الإمارات وادفع نقدًا عند الاستلام.",
      title: "كل ما تحتاجه، من متاجر قريبة منك",
    },
    promotionalBanner: { title: "العروض" },
    quickCategories: { title: "تصفّح الفئات" },
    recommended: { title: "مقترح لك" },
    track: {
      body: "تتبّع الطلبات سيتوفّر مع حسابات العملاء.",
      title: "تتبّع طلبك",
    },
  },
  orders: {
    address: "العنوان",
    backToOrders: "العودة إلى طلباتي",
    browseStores: "تصفّح المتاجر",
    cancelledNote: "تم إلغاء هذا الطلب. الدفع نقدًا عند الاستلام فقط — لم يُؤخذ أي دفع إلكتروني.",
    codTotal: "الإجمالي (الدفع عند الاستلام)",
    delivery: "التوصيل",
    deliveredBy: "التوصيل بواسطة {{company}}",
    deliveryCompany: "شركة التوصيل",
    deliveryFee: "رسوم التوصيل",
    deliveryStatus: "حالة التوصيل",
    empty: {
      body: "ليس لديك أي طلبات بعد.",
      title: "لا توجد طلبات بعد",
    },
    itemCount_one: "منتج واحد",
    itemCount_other: "{{count}} منتجات",
    items: "المنتجات",
    notFound: {
      body: "لم نتمكن من العثور على هذا الطلب، أو أنه لا يخص هذا الحساب.",
      title: "الطلب غير موجود",
    },
    order: "الطلب",
    orderDate: "تاريخ الطلب",
    orderNumber: "رقم الطلب",
    productSubtotal: "المجموع الفرعي للمنتجات",
    status: "الحالة",
    statusLabels: {
      awaiting_trader_confirmation: "بانتظار تأكيد المتجر",
      cancelled: "ملغى",
      completed_external: "مكتمل",
      confirmed: "مؤكد",
      converted_to_delivery: "تم تسليمه للتوصيل",
      draft: "مسودة",
      submitted: "تم الإرسال",
    },
    store: "المتجر",
    summary: "ملخص الطلب",
    title: "طلباتي",
    total: "الإجمالي",
    viewDetails: "عرض التفاصيل",
  },
  product: {
    availability: { available: "متوفر", unavailable: "غير متوفر حاليًا" },
    backToStore: "العودة إلى المتجر",
    brand: "العلامة التجارية",
    code: "رمز المنتج",
    details: "التفاصيل",
    gallery: "صور المنتج",
    imageOf: "صورة {{index}} من {{total}}",
    noImage: "لا تتوفر صورة",
    optionRequired: "مطلوب",
    options: "الخيارات",
    saveAmount: "وفّر {{amount}}",
    share: {
      action: "مشاركة",
      copied: "تم نسخ الرابط",
      unavailable: "انسخ الرابط من شريط العنوان",
    },
    soldBy: "يُباع بواسطة",
    was: "السعر السابق",
  },
  store: {
    about: "عن هذا المتجر",
    businessHours: "ساعات العمل",
    categories: "الفئات",
    closed: "مغلق مؤقتًا",
    contact: "التواصل",
    delivery: "معلومات التوصيل",
    email: "البريد الإلكتروني",
    information: "معلومات المتجر",
    mobile: "الهاتف",
    newStore: "متجر جديد",
    noProducts: {
      body: "لم يُدرج هذا المتجر أي منتجات بعد.",
      title: "لا توجد منتجات بعد",
    },
    open: "مفتوح",
    policies: "السياسات",
    products: "المنتجات",
    returns: "الإرجاع والاستبدال",
    support: "خدمة العملاء",
    terms: "الشروط",
    whatsapp: "واتساب",
  },
  tracking: {
    invalid: "تعذّر التحقق من هذا الطلب بالمعلومات المُدخلة.",
    lead: "أدخل بيانات طلبك للتحقق من حالته.",
    mobile: "رقم جوال العميل",
    orderNumber: "رقم الطلب",
    submit: "التحقق من الطلب",
    submitting: "جارٍ التحقق…",
    title: "تتبّع الطلب",
    token: "رمز التتبّع",
  },
} as const;
