export const en = {
  categories: {
    breadcrumb: "Breadcrumb",
    browseOthers: "Browse other categories",
    empty: {
      body: "Categories will appear here once the marketplace is set up.",
      title: "No categories yet",
    },
    home: "Home",
    noProducts: {
      body: "No products are listed in this category yet.",
      title: "No products yet",
    },
    noStores: {
      body: "No stores are listed in this category yet.",
      title: "No stores yet",
    },
    notFound: {
      body: "We could not find that category.",
      title: "Category not found",
    },
    productCount: "{{count}} product",
    productCount_other: "{{count}} products",
    products: "Products",
    stores: "Stores",
    subcategories: "Subcategories",
    title: "Categories",
    viewAll: "View all",
  },
  common: {
    account: "Account",
    all: "All",
    arabic: "العربية",
    back: "Back",
    cart: "Cart",
    comingSoon: "Coming soon",
    english: "English",
    language: "Language",
    loading: "Loading",
    retry: "Try again",
    search: "Search",
    searchPlaceholder: "Search stores and products",
    skipToContent: "Skip to content",
    viewAll: "View all",
  },
  errors: {
    apiUnavailable: {
      body: "We could not reach the store service. Please try again in a moment.",
      title: "Service unavailable",
    },
    network: {
      body: "Check your connection and try again.",
      title: "Connection problem",
    },
    productNotFound: {
      body: "This product is no longer listed.",
      title: "Product not found",
    },
    storeClosed: {
      body: "This store is temporarily closed and is not taking orders right now.",
      title: "Temporarily closed",
    },
    storeNotFound: {
      body: "We could not find a store at this address.",
      title: "Store not found",
    },
  },
  footer: {
    company: "BluelineGPT",
    customer: "For customers",
    legal: "Legal",
    privacy: "Privacy",
    rights: "BluelineGPT Store",
    support: "Support",
    tagline: "Shop local stores across the UAE and pay cash on delivery.",
    terms: "Terms",
    track: "Track your order",
  },
  home: {
    account: {
      body: "Sign in to see your orders and saved addresses. Customer accounts are coming soon.",
      title: "Your account",
    },
    app: {
      body: "The BluelineGPT Store app is on its way.",
      title: "Shop on the go",
    },
    bestsellers: { title: "Bestsellers" },
    curatedCollections: { title: "Curated collections" },
    empty: {
      body: "No stores are published yet. As soon as a store opens it will appear here.",
      title: "Nothing to show yet",
    },
    featuredStores: {
      subtitle: "Shops open on BluelineGPT right now",
      title: "Featured stores",
    },
    hero: {
      cta: "Browse categories",
      lead: "Shop local stores across the UAE and pay cash on delivery.",
      title: "Everything you need, from stores near you",
    },
    promotionalBanner: { title: "Offers" },
    quickCategories: { title: "Browse categories" },
    recommended: { title: "Recommended for you" },
    track: {
      body: "Order tracking arrives with customer accounts.",
      title: "Track your order",
    },
  },
  product: {
    availability: { available: "Available", unavailable: "Currently unavailable" },
    backToStore: "Back to store",
    brand: "Brand",
    code: "Product code",
    details: "Details",
    gallery: "Product images",
    imageOf: "Image {{index}} of {{total}}",
    noImage: "No image available",
    optionRequired: "Required",
    options: "Options",
    saveAmount: "Save {{amount}}",
    share: {
      action: "Share",
      copied: "Link copied",
      unavailable: "Copy the link from the address bar",
    },
    soldBy: "Sold by",
    was: "Was",
  },
  store: {
    about: "About this store",
    businessHours: "Business hours",
    categories: "Categories",
    closed: "Temporarily closed",
    contact: "Contact",
    delivery: "Delivery information",
    email: "Email",
    information: "Store information",
    mobile: "Phone",
    newStore: "New store",
    noProducts: {
      body: "This store has not listed any products yet.",
      title: "No products yet",
    },
    open: "Open",
    policies: "Policies",
    products: "Products",
    returns: "Returns and exchanges",
    support: "Customer support",
    terms: "Terms",
    whatsapp: "WhatsApp",
  },
} as const;
