export const en = {
  auth: {
    account: {
      addAddress: "Add address",
      addressDefault: "Default",
      addresses: "Addresses",
      addressesEmpty: "No addresses saved yet.",
      businessInfo: "Business Information",
      delete: "Delete",
      edit: "Edit",
      email: "Email",
      logout: "Log out",
      mobile: "Mobile",
      myOrders: "My Orders",
      name: "Name",
      preferredLanguage: "Preferred Language",
      profile: "Profile",
      save: "Save",
      saved: "Saved.",
      setDefault: "Set as default",
      title: "My Account",
    },
    address: {
      area: "Area",
      deliveryInstructions: "Delivery instructions",
      emirate: "Emirate",
      label: "Label",
      locationLink: "Location link",
      mobile: "Mobile",
      recipientName: "Recipient name",
      street: "Address",
    },
    completeReset: "Reset password",
    confirmPassword: "Confirm password",
    createAccount: "Create account",
    email: "Email",
    errors: {
      customer_already_registered: "An account with this mobile number or email already exists.",
      invalid_credentials: "The mobile/email or password is incorrect.",
      invalid_mobile: "Enter a valid UAE mobile number.",
      network_error: "Could not reach the server. Please try again.",
      passwordMismatch: "Passwords do not match.",
      password_reset_token_invalid: "This reset link is invalid or has expired.",
      store_order_not_found: "We couldn't find that Order.",
      store_order_tracking_failed: "We couldn't verify this Order with the information provided.",
      unknown_error: "Something went wrong. Please try again.",
    },
    forgotPassword: "Forgot password?",
    forgotPasswordLead: "Enter your mobile number or email and we will send you a reset link.",
    forgotPasswordTitle: "Reset your password",
    haveAccount: "Already have an account?",
    identifier: "Mobile or email",
    login: "Sign in",
    loginTitle: "Sign in to your account",
    logout: "Log out",
    mobile: "Mobile",
    name: "Name",
    newAccount: "Create account",
    newPassword: "New password",
    noAccount: "Don't have an account?",
    password: "Password",
    register: "Register",
    registerLead: "Create your account to start shopping.",
    registerTitle: "Create your account",
    resetLead: "Choose a new password for your account.",
    resetLinkSent:
      "If an account exists for that mobile number or email, a reset link has been sent.",
    resetSuccess: "Your password has been reset. You can now sign in.",
    resetToken: "Reset token",
    submitReset: "Send reset link",
    termsAcceptance: "I agree to the Terms of Service and Privacy Policy",
  },
  categories: {
    breadcrumb: "Breadcrumb",
    browseOthers: "Browse other categories",
    empty: {
      body: "Categories will appear here once the marketplace is set up.",
      title: "No categories yet",
    },
    home: "Home",
    noProducts: {
      body: "No products are listed in this category yet.",
      title: "No products yet",
    },
    noStores: {
      body: "No stores are listed in this category yet.",
      title: "No stores yet",
    },
    notFound: {
      body: "We could not find that category.",
      title: "Category not found",
    },
    productCount: "{{count}} product",
    productCount_other: "{{count}} products",
    products: "Products",
    stores: "Stores",
    subcategories: "Subcategories",
    title: "Categories",
    viewAll: "View all",
  },
  common: {
    account: "Account",
    all: "All",
    arabic: "العربية",
    back: "Back",
    cart: "Cart",
    comingSoon: "Coming soon",
    english: "English",
    language: "Language",
    loading: "Loading",
    offlineBanner: "You're offline. Some Store features may be unavailable.",
    retry: "Try again",
    search: "Search",
    searchPlaceholder: "Search stores and products",
    skipToContent: "Skip to content",
    viewAll: "View all",
  },
  errors: {
    apiUnavailable: {
      body: "We could not reach the store service. Please try again in a moment.",
      title: "Service unavailable",
    },
    network: {
      body: "Check your connection and try again.",
      title: "Connection problem",
    },
    productNotFound: {
      body: "This product is no longer listed.",
      title: "Product not found",
    },
    storeClosed: {
      body: "This store is temporarily closed and is not taking orders right now.",
      title: "Temporarily closed",
    },
    storeNotFound: {
      body: "We could not find a store at this address.",
      title: "Store not found",
    },
  },
  footer: {
    company: "TawseelHub",
    customer: "For customers",
    legal: "Legal",
    privacy: "Privacy",
    rights: "TawseelHub Store",
    support: "Support",
    tagline: "Shop local stores across the UAE and pay cash on delivery.",
    terms: "Terms",
    track: "Track your order",
  },
  home: {
    account: {
      body: "Sign in to manage your profile and addresses. Order history arrives with Store Orders.",
      title: "Your account",
    },
    app: {
      body: "The TawseelHub Store app is on its way.",
      title: "Shop on the go",
    },
    bestsellers: { title: "Bestsellers" },
    curatedCollections: { title: "Curated collections" },
    empty: {
      body: "No stores are published yet. As soon as a store opens it will appear here.",
      title: "Nothing to show yet",
    },
    featuredStores: {
      subtitle: "Shops open on TawseelHub right now",
      title: "Featured stores",
    },
    hero: {
      cta: "Browse categories",
      lead: "Shop local stores across the UAE and pay cash on delivery.",
      title: "Everything you need, from stores near you",
    },
    promotionalBanner: { title: "Offers" },
    quickCategories: { title: "Browse categories" },
    recommended: { title: "Recommended for you" },
    track: {
      body: "Order tracking arrives with customer accounts.",
      title: "Track your order",
    },
  },
  orders: {
    address: "Address",
    backToOrders: "Back to My Orders",
    browseStores: "Browse Stores",
    cancelledNote: "This Order was cancelled. Cash on Delivery only — no online payment was ever taken.",
    codTotal: "Total (Cash on Delivery)",
    delivery: "Delivery",
    deliveredBy: "Delivered by {{company}}",
    deliveryCompany: "Delivery Company",
    deliveryFee: "Delivery Fee",
    deliveryStatus: "Delivery status",
    empty: {
      body: "You don't have any Orders yet.",
      title: "No Orders yet",
    },
    itemCount_one: "{{count}} item",
    itemCount_other: "{{count}} items",
    items: "Items",
    notFound: {
      body: "We couldn't find that Order, or it doesn't belong to this account.",
      title: "Order not found",
    },
    order: "Order",
    orderDate: "Order Date",
    orderNumber: "Order Number",
    productSubtotal: "Product Subtotal",
    status: "Status",
    statusLabels: {
      awaiting_trader_confirmation: "Waiting for the Store to confirm",
      cancelled: "Cancelled",
      completed_external: "Completed",
      confirmed: "Confirmed",
      converted_to_delivery: "Handed to delivery",
      draft: "Draft",
      submitted: "Submitted",
    },
    store: "Store",
    summary: "Order Summary",
    title: "My Orders",
    total: "Total",
    viewDetails: "View Details",
  },
  product: {
    availability: { available: "Available", unavailable: "Currently unavailable" },
    backToStore: "Back to store",
    brand: "Brand",
    code: "Product code",
    details: "Details",
    gallery: "Product images",
    imageOf: "Image {{index}} of {{total}}",
    noImage: "No image available",
    optionRequired: "Required",
    options: "Options",
    saveAmount: "Save {{amount}}",
    share: {
      action: "Share",
      copied: "Link copied",
      unavailable: "Copy the link from the address bar",
    },
    soldBy: "Sold by",
    was: "Was",
  },
  store: {
    about: "About this store",
    businessHours: "Business hours",
    categories: "Categories",
    closed: "Temporarily closed",
    contact: "Contact",
    delivery: "Delivery information",
    email: "Email",
    information: "Store information",
    mobile: "Phone",
    newStore: "New store",
    noProducts: {
      body: "This store has not listed any products yet.",
      title: "No products yet",
    },
    open: "Open",
    policies: "Policies",
    products: "Products",
    returns: "Returns and exchanges",
    support: "Customer support",
    terms: "Terms",
    whatsapp: "WhatsApp",
  },
  tracking: {
    invalid: "We couldn't verify this Order with the information provided.",
    lead: "Enter your Order details to check its status.",
    mobile: "Customer Mobile",
    orderNumber: "Order Number",
    submit: "Verify Order",
    submitting: "Verifying…",
    title: "Track Order",
    token: "Tracking Code",
  },
} as const;
